// Code generated by wlbgen; DO NOT EDIT.

// Upstream protocol copyright and license:
// Copyright © 2016 Yong Bakos
// Copyright © 2015 Jason Ekstrand
// Copyright © 2015 Jonas Ådahl
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package fullscreenshell

import (
	"fmt"
	wayland "github.com/bnema/go-wayland-bindings/server/wayland"
	"github.com/bnema/purego-libwayland/server"
)

var ZwpFullscreenShellV1Interface *server.Interface
var ZwpFullscreenShellModeFeedbackV1Interface *server.Interface

func init() {
	ZwpFullscreenShellV1Interface = &server.Interface{Name: "zwp_fullscreen_shell_v1", Version: 1}
	ZwpFullscreenShellModeFeedbackV1Interface = &server.Interface{Name: "zwp_fullscreen_shell_mode_feedback_v1", Version: 1}
	ZwpFullscreenShellV1Interface.Requests = []server.Message{
		{Name: "release", Signature: "", Types: []*server.Interface{}},
		{Name: "present_surface", Signature: "?ou?o", Types: []*server.Interface{wayland.SurfaceInterface, nil, wayland.OutputInterface}},
		{Name: "present_surface_for_mode", Signature: "ooin", Types: []*server.Interface{wayland.SurfaceInterface, wayland.OutputInterface, nil, ZwpFullscreenShellModeFeedbackV1Interface}},
	}
	ZwpFullscreenShellV1Interface.Events = []server.Message{
		{Name: "capability", Signature: "u", Types: []*server.Interface{nil}},
	}
	ZwpFullscreenShellModeFeedbackV1Interface.Requests = []server.Message{}
	ZwpFullscreenShellModeFeedbackV1Interface.Events = []server.Message{
		{Name: "mode_successful", Signature: "", Types: []*server.Interface{}},
		{Name: "mode_failed", Signature: "", Types: []*server.Interface{}},
		{Name: "present_cancelled", Signature: "", Types: []*server.Interface{}},
	}
	if err := server.NewInterfaces(ZwpFullscreenShellV1Interface, ZwpFullscreenShellModeFeedbackV1Interface); err != nil {
		panic(err)
	}
}

// ZwpFullscreenShellV1 displays a single surface per output.
type ZwpFullscreenShellV1 struct{ *server.Resource }

func WrapZwpFullscreenShellV1(r *server.Resource) *ZwpFullscreenShellV1 {
	if r == nil {
		return nil
	}
	return &ZwpFullscreenShellV1{r}
}

const ZwpFullscreenShellV1RequestRelease uint32 = 0
const ZwpFullscreenShellV1RequestPresentSurface uint32 = 1
const ZwpFullscreenShellV1RequestPresentSurfaceForMode uint32 = 2
const ZwpFullscreenShellV1EventCapability uint32 = 0

// ZwpFullscreenShellV1Capability capabilities advertised by the compositor.
type ZwpFullscreenShellV1Capability uint32

const (
	ZwpFullscreenShellV1CapabilityArbitraryModes ZwpFullscreenShellV1Capability = 1
	ZwpFullscreenShellV1CapabilityCursorPlane    ZwpFullscreenShellV1Capability = 2
)

// ZwpFullscreenShellV1PresentMethod different method to set the surface fullscreen.
type ZwpFullscreenShellV1PresentMethod uint32

const (
	ZwpFullscreenShellV1PresentMethodDefault  ZwpFullscreenShellV1PresentMethod = 0
	ZwpFullscreenShellV1PresentMethodCenter   ZwpFullscreenShellV1PresentMethod = 1
	ZwpFullscreenShellV1PresentMethodZoom     ZwpFullscreenShellV1PresentMethod = 2
	ZwpFullscreenShellV1PresentMethodZoomCrop ZwpFullscreenShellV1PresentMethod = 3
	ZwpFullscreenShellV1PresentMethodStretch  ZwpFullscreenShellV1PresentMethod = 4
)

// ZwpFullscreenShellV1Error wl_fullscreen_shell error values.
type ZwpFullscreenShellV1Error uint32

const (
	ZwpFullscreenShellV1ErrorInvalidMethod ZwpFullscreenShellV1Error = 0
	ZwpFullscreenShellV1ErrorRole          ZwpFullscreenShellV1Error = 1
)

// ZwpFullscreenShellV1Handler handles zwp_fullscreen_shell_v1 requests.
type ZwpFullscreenShellV1Handler interface {
	Release(self *ZwpFullscreenShellV1)
	PresentSurface(self *ZwpFullscreenShellV1, surface *wayland.Surface, method uint32, output *wayland.Output)
	PresentSurfaceForMode(self *ZwpFullscreenShellV1, surface *wayland.Surface, output *wayland.Output, framerate int32, feedback uint32)
}

func NewZwpFullscreenShellV1(c server.Client, version int32, id uint32, h ZwpFullscreenShellV1Handler) (*ZwpFullscreenShellV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for zwp_fullscreen_shell_v1")
	}
	var self *ZwpFullscreenShellV1
	r, err := c.CreateResource(ZwpFullscreenShellV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Release(self)
			self.Destroy()
		case 1:
			h.PresentSurface(self, wayland.WrapSurface(args[0].Resource()), args[1].Uint(), wayland.WrapOutput(args[2].Resource()))
		case 2:
			h.PresentSurfaceForMode(self, wayland.WrapSurface(args[0].Resource()), wayland.WrapOutput(args[1].Resource()), args[2].Int(), args[3].NewID())
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapZwpFullscreenShellV1(r)
	r.Data = self
	return self, nil
}

// SendCapability advertises a capability of the compositor.
func (self *ZwpFullscreenShellV1) SendCapability(capability uint32) {
	self.PostEvent(ZwpFullscreenShellV1EventCapability, server.Uint(capability))
}
func NewZwpFullscreenShellV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(ZwpFullscreenShellV1Interface, version, bind)
}

// ZwpFullscreenShellModeFeedbackV1 .
type ZwpFullscreenShellModeFeedbackV1 struct{ *server.Resource }

func WrapZwpFullscreenShellModeFeedbackV1(r *server.Resource) *ZwpFullscreenShellModeFeedbackV1 {
	if r == nil {
		return nil
	}
	return &ZwpFullscreenShellModeFeedbackV1{r}
}

const ZwpFullscreenShellModeFeedbackV1EventModeSuccessful uint32 = 0
const ZwpFullscreenShellModeFeedbackV1EventModeFailed uint32 = 1
const ZwpFullscreenShellModeFeedbackV1EventPresentCancelled uint32 = 2

// ZwpFullscreenShellModeFeedbackV1Handler handles zwp_fullscreen_shell_mode_feedback_v1 requests.
type ZwpFullscreenShellModeFeedbackV1Handler interface {
}

func NewZwpFullscreenShellModeFeedbackV1(c server.Client, version int32, id uint32, h ZwpFullscreenShellModeFeedbackV1Handler) (*ZwpFullscreenShellModeFeedbackV1, error) {
	var self *ZwpFullscreenShellModeFeedbackV1
	r, err := c.CreateResource(ZwpFullscreenShellModeFeedbackV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapZwpFullscreenShellModeFeedbackV1(r)
	r.Data = self
	return self, nil
}

// SendModeSuccessful mode switch succeeded.
func (self *ZwpFullscreenShellModeFeedbackV1) SendModeSuccessful() {
	self.PostEvent(ZwpFullscreenShellModeFeedbackV1EventModeSuccessful)
}

// SendModeFailed mode switch failed.
func (self *ZwpFullscreenShellModeFeedbackV1) SendModeFailed() {
	self.PostEvent(ZwpFullscreenShellModeFeedbackV1EventModeFailed)
}

// SendPresentCancelled mode switch cancelled.
func (self *ZwpFullscreenShellModeFeedbackV1) SendPresentCancelled() {
	self.PostEvent(ZwpFullscreenShellModeFeedbackV1EventPresentCancelled)
}
func NewZwpFullscreenShellModeFeedbackV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(ZwpFullscreenShellModeFeedbackV1Interface, version, bind)
}
func resourceOf(v interface{ GetResource() *server.Resource }) *server.Resource {
	if v == nil {
		return nil
	}
	return v.GetResource()
}
func (self *ZwpFullscreenShellV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *ZwpFullscreenShellModeFeedbackV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
