// Code generated by wlbgen. DO NOT EDIT.
// Protocol: xdg_dialog_v1
// Source: xdg-dialog-v1.xml

// Upstream protocol copyright and license:
// Copyright © 2023 Carlos Garnacho
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package xdgdialog

import (
	cross_xdg_toplevel "github.com/bnema/go-wayland-bindings/client/xdgshell"
	"github.com/bnema/wlturbo/wl"
)

// ERROR_ALREADY_USED is the error already_used value.
const ERROR_ALREADY_USED = 0

// XdgWmDialogInterface is the protocol interface name.
const XdgWmDialogInterface = "xdg_wm_dialog_v1"

// XdgWmDialog is the generated binding for xdg_wm_dialog_v1 version 1.
type XdgWmDialog struct {
	wl.BaseProxy
}

// NewXdgWmDialog returns an unbound XdgWmDialog.
func NewXdgWmDialog(ctx *wl.Context) *XdgWmDialog {
	obj := &XdgWmDialog{}
	obj.SetContext(ctx)
	ctx.Register(obj)
	return obj
}

// Destroys the xdg_wm_dialog_v1 object. This does not affect the xdg_dialog_v1 objects generated through it.
func (o *XdgWmDialog) Destroy() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 0, Name: "xdg_wm_dialog_v1.destroy", Destructor: true}); err != nil {
		return err
	}
	return nil
}

// Creates a xdg_dialog_v1 object for the given toplevel. See the interface description for more details. Compositors must raise an already_used error if clients attempt to create multiple xdg_dialog_v1 objects for the same xdg_toplevel.
func (o *XdgWmDialog) GetXdgDialog(toplevel *cross_xdg_toplevel.XdgToplevel) (*XdgDialog, error) {
	var arg1 wl.Object
	if toplevel != nil {
		arg1 = toplevel
	}
	child := &XdgDialog{}
	child.SetContext(o.Context())
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 1, Name: "xdg_wm_dialog_v1.get_xdg_dialog", Child: child}, wl.ArgObject(child), wl.ArgObject(arg1)); err != nil {
		return nil, err
	}
	return child, nil
}

// EventSignature returns the declared event argument types in wire order.
func (o *XdgWmDialog) EventSignature(opcode uint16) (string, bool) {
	switch opcode {
	default:
		return "", false
	}
}

// Dispatch decodes one event on xdg_wm_dialog_v1 and calls the registered handlers.
func (o *XdgWmDialog) Dispatch(event *wl.Event) {
	switch event.Opcode {
	default:
	}
}

// XdgDialogInterface is the protocol interface name.
const XdgDialogInterface = "xdg_dialog_v1"

// XdgDialog is the generated binding for xdg_dialog_v1 version 1.
type XdgDialog struct {
	wl.BaseProxy
}

// NewXdgDialog returns an unbound XdgDialog.
func NewXdgDialog(ctx *wl.Context) *XdgDialog {
	obj := &XdgDialog{}
	obj.SetContext(ctx)
	ctx.Register(obj)
	return obj
}

// Destroys the xdg_dialog_v1 object. If this object is destroyed before the related xdg_toplevel, the compositor should unapply its effects.
func (o *XdgDialog) Destroy() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 0, Name: "xdg_dialog_v1.destroy", Destructor: true}); err != nil {
		return err
	}
	return nil
}

// Hints that the dialog has "modal" behavior. Modal dialogs typically require to be fully addressed by the user (i.e. closed) before resuming interaction with the parent toplevel, and may require a distinct presentation. Clients must implement the logic to filter events in the parent toplevel on their own. Compositors may choose any policy in event delivery to the parent toplevel, from delivering all events unfiltered to using them for internal consumption.
func (o *XdgDialog) SetModal() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 1, Name: "xdg_dialog_v1.set_modal"}); err != nil {
		return err
	}
	return nil
}

// Drops the hint that this dialog has "modal" behavior. See xdg_dialog_v1.set_modal for more details.
func (o *XdgDialog) UnsetModal() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 2, Name: "xdg_dialog_v1.unset_modal"}); err != nil {
		return err
	}
	return nil
}

// EventSignature returns the declared event argument types in wire order.
func (o *XdgDialog) EventSignature(opcode uint16) (string, bool) {
	switch opcode {
	default:
		return "", false
	}
}

// Dispatch decodes one event on xdg_dialog_v1 and calls the registered handlers.
func (o *XdgDialog) Dispatch(event *wl.Event) {
	switch event.Opcode {
	default:
	}
}
