// Code generated by wlbgen; DO NOT EDIT.
package wlrinputinhibitor

import (
	"fmt"
	"github.com/bnema/purego-libwayland/server"
)

var ZwlrInputInhibitManagerV1Interface *server.Interface
var ZwlrInputInhibitorV1Interface *server.Interface

func init() {
	ZwlrInputInhibitManagerV1Interface = &server.Interface{Name: "zwlr_input_inhibit_manager_v1", Version: 1}
	ZwlrInputInhibitorV1Interface = &server.Interface{Name: "zwlr_input_inhibitor_v1", Version: 1}
	ZwlrInputInhibitManagerV1Interface.Requests = []server.Message{
		{Name: "get_inhibitor", Signature: "n", Types: []*server.Interface{ZwlrInputInhibitorV1Interface}},
	}
	ZwlrInputInhibitManagerV1Interface.Events = []server.Message{}
	ZwlrInputInhibitorV1Interface.Requests = []server.Message{
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
	}
	ZwlrInputInhibitorV1Interface.Events = []server.Message{}
	if err := server.NewInterfaces(ZwlrInputInhibitManagerV1Interface, ZwlrInputInhibitorV1Interface); err != nil {
		panic(err)
	}
}

// ZwlrInputInhibitManagerV1 inhibits input events to other clients.
type ZwlrInputInhibitManagerV1 struct{ *server.Resource }

func WrapZwlrInputInhibitManagerV1(r *server.Resource) *ZwlrInputInhibitManagerV1 {
	if r == nil {
		return nil
	}
	return &ZwlrInputInhibitManagerV1{r}
}

const ZwlrInputInhibitManagerV1RequestGetInhibitor uint32 = 0

// ZwlrInputInhibitManagerV1Error .
type ZwlrInputInhibitManagerV1Error uint32

const (
	ZwlrInputInhibitManagerV1ErrorAlreadyInhibited ZwlrInputInhibitManagerV1Error = 0
)

// ZwlrInputInhibitManagerV1Handler handles zwlr_input_inhibit_manager_v1 requests.
type ZwlrInputInhibitManagerV1Handler interface {
	GetInhibitor(self *ZwlrInputInhibitManagerV1, id uint32)
}

func NewZwlrInputInhibitManagerV1(c server.Client, version int32, id uint32, h ZwlrInputInhibitManagerV1Handler) (*ZwlrInputInhibitManagerV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for zwlr_input_inhibit_manager_v1")
	}
	var self *ZwlrInputInhibitManagerV1
	r, err := c.CreateResource(ZwlrInputInhibitManagerV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.GetInhibitor(self, args[0].NewID())
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapZwlrInputInhibitManagerV1(r)
	r.Data = self
	return self, nil
}
func NewZwlrInputInhibitManagerV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(ZwlrInputInhibitManagerV1Interface, version, bind)
}

// ZwlrInputInhibitorV1 inhibits input to other clients.
type ZwlrInputInhibitorV1 struct{ *server.Resource }

func WrapZwlrInputInhibitorV1(r *server.Resource) *ZwlrInputInhibitorV1 {
	if r == nil {
		return nil
	}
	return &ZwlrInputInhibitorV1{r}
}

const ZwlrInputInhibitorV1RequestDestroy uint32 = 0

// ZwlrInputInhibitorV1Handler handles zwlr_input_inhibitor_v1 requests.
type ZwlrInputInhibitorV1Handler interface {
	Destroy(self *ZwlrInputInhibitorV1)
}

func NewZwlrInputInhibitorV1(c server.Client, version int32, id uint32, h ZwlrInputInhibitorV1Handler) (*ZwlrInputInhibitorV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for zwlr_input_inhibitor_v1")
	}
	var self *ZwlrInputInhibitorV1
	r, err := c.CreateResource(ZwlrInputInhibitorV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Destroy(self)
			self.Destroy()
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapZwlrInputInhibitorV1(r)
	r.Data = self
	return self, nil
}
func NewZwlrInputInhibitorV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(ZwlrInputInhibitorV1Interface, version, bind)
}
func resourceOf(v interface{ GetResource() *server.Resource }) *server.Resource {
	if v == nil {
		return nil
	}
	return v.GetResource()
}
func (self *ZwlrInputInhibitManagerV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *ZwlrInputInhibitorV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
