// Code generated by wlbgen. DO NOT EDIT.
// Protocol: xwayland_keyboard_grab_unstable_v1
// Source: xwayland-keyboard-grab-unstable-v1.xml

// Upstream protocol copyright and license:
// Copyright © 2017 Red Hat Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package xwaylandkeyboardgrab

import (
	cross_wl_seat "github.com/bnema/go-wayland-bindings/client/wayland"
	cross_wl_surface "github.com/bnema/go-wayland-bindings/client/wayland"
	"github.com/bnema/wlturbo/wl"
)

// XwaylandKeyboardGrabManagerInterface is the protocol interface name.
const XwaylandKeyboardGrabManagerInterface = "zwp_xwayland_keyboard_grab_manager_v1"

// XwaylandKeyboardGrabManager is the generated binding for zwp_xwayland_keyboard_grab_manager_v1 version 1.
type XwaylandKeyboardGrabManager struct {
	wl.BaseProxy
}

// NewXwaylandKeyboardGrabManager returns an unbound XwaylandKeyboardGrabManager.
func NewXwaylandKeyboardGrabManager(ctx *wl.Context) *XwaylandKeyboardGrabManager {
	obj := &XwaylandKeyboardGrabManager{}
	obj.SetContext(ctx)
	ctx.Register(obj)
	return obj
}

// Destroy the keyboard grab manager.
func (o *XwaylandKeyboardGrabManager) Destroy() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 0, Name: "zwp_xwayland_keyboard_grab_manager_v1.destroy", Destructor: true}); err != nil {
		return err
	}
	return nil
}

// The grab_keyboard request asks for a grab of the keyboard, forcing the keyboard focus for the given seat upon the given surface. The protocol provides no guarantee that the grab is ever satisfied, and does not require the compositor to send an error if the grab cannot ever be satisfied. It is thus possible to request a keyboard grab that will never be effective. The protocol: * does not guarantee that the grab itself is applied for a surface, the grab request may be silently ignored by the compositor, * does not guarantee that any events are sent to this client even if the grab is applied to a surface, * does not guarantee that events sent to this client are exhaustive, a compositor may filter some events for its own consumption, * does not guarantee that events sent to this client are continuous, a compositor may change and reroute keyboard events while the grab is nominally active.
func (o *XwaylandKeyboardGrabManager) GrabKeyboard(surface *cross_wl_surface.Surface, seat *cross_wl_seat.Seat) (*XwaylandKeyboardGrab, error) {
	var arg1 wl.Object
	if surface != nil {
		arg1 = surface
	}
	var arg2 wl.Object
	if seat != nil {
		arg2 = seat
	}
	child := &XwaylandKeyboardGrab{}
	child.SetContext(o.Context())
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 1, Name: "zwp_xwayland_keyboard_grab_manager_v1.grab_keyboard", Child: child}, wl.ArgObject(child), wl.ArgObject(arg1), wl.ArgObject(arg2)); err != nil {
		return nil, err
	}
	return child, nil
}

// EventSignature returns the declared event argument types in wire order.
func (o *XwaylandKeyboardGrabManager) EventSignature(opcode uint16) (string, bool) {
	switch opcode {
	default:
		return "", false
	}
}

// Dispatch decodes one event on zwp_xwayland_keyboard_grab_manager_v1 and calls the registered handlers.
func (o *XwaylandKeyboardGrabManager) Dispatch(event *wl.Event) {
	switch event.Opcode {
	default:
	}
}

// XwaylandKeyboardGrabInterface is the protocol interface name.
const XwaylandKeyboardGrabInterface = "zwp_xwayland_keyboard_grab_v1"

// XwaylandKeyboardGrab is the generated binding for zwp_xwayland_keyboard_grab_v1 version 1.
type XwaylandKeyboardGrab struct {
	wl.BaseProxy
}

// NewXwaylandKeyboardGrab returns an unbound XwaylandKeyboardGrab.
func NewXwaylandKeyboardGrab(ctx *wl.Context) *XwaylandKeyboardGrab {
	obj := &XwaylandKeyboardGrab{}
	obj.SetContext(ctx)
	ctx.Register(obj)
	return obj
}

// Destroy the grabbed keyboard object. If applicable, the compositor will ungrab the keyboard.
func (o *XwaylandKeyboardGrab) Destroy() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 0, Name: "zwp_xwayland_keyboard_grab_v1.destroy", Destructor: true}); err != nil {
		return err
	}
	return nil
}

// EventSignature returns the declared event argument types in wire order.
func (o *XwaylandKeyboardGrab) EventSignature(opcode uint16) (string, bool) {
	switch opcode {
	default:
		return "", false
	}
}

// Dispatch decodes one event on zwp_xwayland_keyboard_grab_v1 and calls the registered handlers.
func (o *XwaylandKeyboardGrab) Dispatch(event *wl.Event) {
	switch event.Opcode {
	default:
	}
}
