// Code generated by wlbgen; DO NOT EDIT.

// Upstream protocol copyright and license:
// Copyright © 2015 Samsung Electronics Co., Ltd
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package idleinhibit

import (
	"fmt"
	wayland "github.com/bnema/go-wayland-bindings/server/wayland"
	"github.com/bnema/purego-libwayland/server"
)

var ZwpIdleInhibitManagerV1Interface *server.Interface
var ZwpIdleInhibitorV1Interface *server.Interface

func init() {
	ZwpIdleInhibitManagerV1Interface = &server.Interface{Name: "zwp_idle_inhibit_manager_v1", Version: 1}
	ZwpIdleInhibitorV1Interface = &server.Interface{Name: "zwp_idle_inhibitor_v1", Version: 1}
	ZwpIdleInhibitManagerV1Interface.Requests = []server.Message{
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
		{Name: "create_inhibitor", Signature: "no", Types: []*server.Interface{ZwpIdleInhibitorV1Interface, wayland.SurfaceInterface}},
	}
	ZwpIdleInhibitManagerV1Interface.Events = []server.Message{}
	ZwpIdleInhibitorV1Interface.Requests = []server.Message{
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
	}
	ZwpIdleInhibitorV1Interface.Events = []server.Message{}
	if err := server.NewInterfaces(ZwpIdleInhibitManagerV1Interface, ZwpIdleInhibitorV1Interface); err != nil {
		panic(err)
	}
}

// ZwpIdleInhibitManagerV1 control behavior when display idles.
type ZwpIdleInhibitManagerV1 struct{ *server.Resource }

func WrapZwpIdleInhibitManagerV1(r *server.Resource) *ZwpIdleInhibitManagerV1 {
	if r == nil {
		return nil
	}
	return &ZwpIdleInhibitManagerV1{r}
}

const ZwpIdleInhibitManagerV1RequestDestroy uint32 = 0
const ZwpIdleInhibitManagerV1RequestCreateInhibitor uint32 = 1

// ZwpIdleInhibitManagerV1Handler handles zwp_idle_inhibit_manager_v1 requests.
type ZwpIdleInhibitManagerV1Handler interface {
	Destroy(self *ZwpIdleInhibitManagerV1)
	CreateInhibitor(self *ZwpIdleInhibitManagerV1, id uint32, surface *wayland.Surface)
}

func NewZwpIdleInhibitManagerV1(c server.Client, version int32, id uint32, h ZwpIdleInhibitManagerV1Handler) (*ZwpIdleInhibitManagerV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for zwp_idle_inhibit_manager_v1")
	}
	var self *ZwpIdleInhibitManagerV1
	r, err := c.CreateResource(ZwpIdleInhibitManagerV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Destroy(self)
			self.Destroy()
		case 1:
			h.CreateInhibitor(self, args[0].NewID(), wayland.WrapSurface(args[1].Resource()))
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapZwpIdleInhibitManagerV1(r)
	r.Data = self
	return self, nil
}
func NewZwpIdleInhibitManagerV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(ZwpIdleInhibitManagerV1Interface, version, bind)
}

// ZwpIdleInhibitorV1 context object for inhibiting idle behavior.
type ZwpIdleInhibitorV1 struct{ *server.Resource }

func WrapZwpIdleInhibitorV1(r *server.Resource) *ZwpIdleInhibitorV1 {
	if r == nil {
		return nil
	}
	return &ZwpIdleInhibitorV1{r}
}

const ZwpIdleInhibitorV1RequestDestroy uint32 = 0

// ZwpIdleInhibitorV1Handler handles zwp_idle_inhibitor_v1 requests.
type ZwpIdleInhibitorV1Handler interface {
	Destroy(self *ZwpIdleInhibitorV1)
}

func NewZwpIdleInhibitorV1(c server.Client, version int32, id uint32, h ZwpIdleInhibitorV1Handler) (*ZwpIdleInhibitorV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for zwp_idle_inhibitor_v1")
	}
	var self *ZwpIdleInhibitorV1
	r, err := c.CreateResource(ZwpIdleInhibitorV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Destroy(self)
			self.Destroy()
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapZwpIdleInhibitorV1(r)
	r.Data = self
	return self, nil
}
func NewZwpIdleInhibitorV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(ZwpIdleInhibitorV1Interface, version, bind)
}
func resourceOf(v interface{ GetResource() *server.Resource }) *server.Resource {
	if v == nil {
		return nil
	}
	return v.GetResource()
}
func (self *ZwpIdleInhibitManagerV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *ZwpIdleInhibitorV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
