// Code generated by wlbgen. DO NOT EDIT.
// Protocol: xdg_toplevel_tag_v1
// Source: xdg-toplevel-tag-v1.xml

// Upstream protocol copyright and license:
// Copyright © 2024 Xaver Hugl
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package xdgtopleveltag

import (
	cross_xdg_toplevel "github.com/bnema/go-wayland-bindings/client/xdgshell"
	"github.com/bnema/wlturbo/wl"
)

// XdgToplevelTagManagerInterface is the protocol interface name.
const XdgToplevelTagManagerInterface = "xdg_toplevel_tag_manager_v1"

// XdgToplevelTagManager is the generated binding for xdg_toplevel_tag_manager_v1 version 1.
type XdgToplevelTagManager struct {
	wl.BaseProxy
}

// NewXdgToplevelTagManager returns an unbound XdgToplevelTagManager.
func NewXdgToplevelTagManager(ctx *wl.Context) *XdgToplevelTagManager {
	obj := &XdgToplevelTagManager{}
	obj.SetContext(ctx)
	ctx.Register(obj)
	return obj
}

// Destroy this toplevel tag manager object. This request has no other effects.
func (o *XdgToplevelTagManager) Destroy() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 0, Name: "xdg_toplevel_tag_manager_v1.destroy", Destructor: true}); err != nil {
		return err
	}
	return nil
}

// Set a tag for a toplevel. The tag may be shown to the user in UI, so it's preferable for it to be human readable, but it must be suitable for configuration files and should not be translated. Suitable tags would for example be "main window", "settings", "e-mail composer" or similar. The tag does not need to be unique across applications, and the client may set the same tag for multiple windows, for example if the user has opened the same UI twice. How the potentially resulting conflicts are handled is compositor policy. The client should set the tag as part of the initial commit on the associated toplevel, but it may set it at any time afterwards as well, for example if the purpose of the toplevel changes.
func (o *XdgToplevelTagManager) SetToplevelTag(toplevel *cross_xdg_toplevel.XdgToplevel, tag string) error {
	var arg0 wl.Object
	if toplevel != nil {
		arg0 = toplevel
	}
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 1, Name: "xdg_toplevel_tag_manager_v1.set_toplevel_tag"}, wl.ArgObject(arg0), wl.ArgString(tag)); err != nil {
		return err
	}
	return nil
}

// Set a description for a toplevel. This description may be shown to the user in UI or read by a screen reader for accessibility purposes, and should be translated. It is recommended to make the description the translation of the tag. The client should set the description as part of the initial commit on the associated toplevel, but it may set it at any time afterwards as well, for example if the purpose of the toplevel changes.
func (o *XdgToplevelTagManager) SetToplevelDescription(toplevel *cross_xdg_toplevel.XdgToplevel, description string) error {
	var arg0 wl.Object
	if toplevel != nil {
		arg0 = toplevel
	}
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 2, Name: "xdg_toplevel_tag_manager_v1.set_toplevel_description"}, wl.ArgObject(arg0), wl.ArgString(description)); err != nil {
		return err
	}
	return nil
}

// EventSignature returns the declared event argument types in wire order.
func (o *XdgToplevelTagManager) EventSignature(opcode uint16) (string, bool) {
	switch opcode {
	default:
		return "", false
	}
}

// Dispatch decodes one event on xdg_toplevel_tag_manager_v1 and calls the registered handlers.
func (o *XdgToplevelTagManager) Dispatch(event *wl.Event) {
	switch event.Opcode {
	default:
	}
}
