// Code generated by wlbgen. DO NOT EDIT.
// Protocol: wlr_export_dmabuf_unstable_v1
// Source: wlr-export-dmabuf-unstable-v1.xml

// Upstream protocol copyright and license:
// Copyright © 2018 Rostislav Pehlivanov
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package wlrexportdmabuf

import (
	"sync"

	cross_wl_output "github.com/bnema/go-wayland-bindings/client/wayland"
	"github.com/bnema/wlturbo/wl"
)

// FLAGS_TRANSIENT is the flags transient value.
const FLAGS_TRANSIENT = 0x1

// CANCEL_REASON_TEMPORARY is the cancel_reason temporary value.
const CANCEL_REASON_TEMPORARY = 0

// CANCEL_REASON_PERMANENT is the cancel_reason permanent value.
const CANCEL_REASON_PERMANENT = 1

// CANCEL_REASON_RESIZING is the cancel_reason resizing value.
const CANCEL_REASON_RESIZING = 2

// ExportDmabufManagerInterface is the protocol interface name.
const ExportDmabufManagerInterface = "zwlr_export_dmabuf_manager_v1"

// ExportDmabufManager is the generated binding for zwlr_export_dmabuf_manager_v1 version 1.
type ExportDmabufManager struct {
	wl.BaseProxy
}

// NewExportDmabufManager returns an unbound ExportDmabufManager.
func NewExportDmabufManager(ctx *wl.Context) *ExportDmabufManager {
	obj := &ExportDmabufManager{}
	obj.SetContext(ctx)
	ctx.Register(obj)
	return obj
}

// Capture the next frame of an entire output.
func (o *ExportDmabufManager) CaptureOutput(overlayCursor int32, output *cross_wl_output.Output) (*ExportDmabufFrame, error) {
	var arg2 wl.Object
	if output != nil {
		arg2 = output
	}
	child := &ExportDmabufFrame{}
	child.SetContext(o.Context())
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 0, Name: "zwlr_export_dmabuf_manager_v1.capture_output", Child: child}, wl.ArgObject(child), wl.ArgInt(overlayCursor), wl.ArgObject(arg2)); err != nil {
		return nil, err
	}
	return child, nil
}

// All objects created by the manager will still remain valid, until their appropriate destroy request has been called.
func (o *ExportDmabufManager) Destroy() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 1, Name: "zwlr_export_dmabuf_manager_v1.destroy", Destructor: true}); err != nil {
		return err
	}
	return nil
}

// EventSignature returns the declared event argument types in wire order.
func (o *ExportDmabufManager) EventSignature(opcode uint16) (string, bool) {
	switch opcode {
	default:
		return "", false
	}
}

// Dispatch decodes one event on zwlr_export_dmabuf_manager_v1 and calls the registered handlers.
func (o *ExportDmabufManager) Dispatch(event *wl.Event) {
	switch event.Opcode {
	default:
	}
}

// ExportDmabufFrameInterface is the protocol interface name.
const ExportDmabufFrameInterface = "zwlr_export_dmabuf_frame_v1"

// ExportDmabufFrame is the generated binding for zwlr_export_dmabuf_frame_v1 version 1.
type ExportDmabufFrame struct {
	wl.BaseProxy
	// handlersMu guards the handler slices: a client may register or replace
	// handlers while another goroutine dispatches events.
	handlersMu sync.Mutex
	onFrame    []func(width uint32, height uint32, offsetX uint32, offsetY uint32, bufferFlags uint32, flags uint32, format uint32, modHigh uint32, modLow uint32, numObjects uint32)
	onObject   []func(index uint32, fd *wl.OwnedFD, size uint32, offset uint32, stride uint32, planeIndex uint32)
	onReady    []func(tvSecHi uint32, tvSecLo uint32, tvNsec uint32)
	onCancel   []func(reason uint32)
}

// NewExportDmabufFrame returns an unbound ExportDmabufFrame.
func NewExportDmabufFrame(ctx *wl.Context) *ExportDmabufFrame {
	obj := &ExportDmabufFrame{}
	obj.SetContext(ctx)
	ctx.Register(obj)
	return obj
}

// Unreferences the frame. This request must be called as soon as it's no longer used. It can be called at any time by the client. The client will still have to close any FDs it has been given.
func (o *ExportDmabufFrame) Destroy() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 0, Name: "zwlr_export_dmabuf_frame_v1.destroy", Destructor: true}); err != nil {
		return err
	}
	return nil
}

// OnFrame registers a handler for the frame event.
//
// Handlers are appended, so a second call adds another handler rather than
// replacing the first. Registration is safe while another goroutine dispatches.
func (o *ExportDmabufFrame) OnFrame(handler func(width uint32, height uint32, offsetX uint32, offsetY uint32, bufferFlags uint32, flags uint32, format uint32, modHigh uint32, modLow uint32, numObjects uint32)) {
	if handler == nil {
		return
	}
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	o.onFrame = append(o.onFrame, handler)
}

// handlersForFrame returns the handlers registered for frame, taken
// under the lock so a handler may register another handler while events are
// being dispatched.
func (o *ExportDmabufFrame) handlersForFrame() []func(width uint32, height uint32, offsetX uint32, offsetY uint32, bufferFlags uint32, flags uint32, format uint32, modHigh uint32, modLow uint32, numObjects uint32) {
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	return o.onFrame
}

// OnObject registers a handler for the object event.
//
// Handlers are appended, so a second call adds another handler rather than
// replacing the first. Registration is safe while another goroutine dispatches.
func (o *ExportDmabufFrame) OnObject(handler func(index uint32, fd *wl.OwnedFD, size uint32, offset uint32, stride uint32, planeIndex uint32)) {
	if handler == nil {
		return
	}
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	o.onObject = append(o.onObject, handler)
}

// handlersForObject returns the handlers registered for object, taken
// under the lock so a handler may register another handler while events are
// being dispatched.
func (o *ExportDmabufFrame) handlersForObject() []func(index uint32, fd *wl.OwnedFD, size uint32, offset uint32, stride uint32, planeIndex uint32) {
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	return o.onObject
}

// OnReady registers a handler for the ready event.
//
// Handlers are appended, so a second call adds another handler rather than
// replacing the first. Registration is safe while another goroutine dispatches.
func (o *ExportDmabufFrame) OnReady(handler func(tvSecHi uint32, tvSecLo uint32, tvNsec uint32)) {
	if handler == nil {
		return
	}
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	o.onReady = append(o.onReady, handler)
}

// handlersForReady returns the handlers registered for ready, taken
// under the lock so a handler may register another handler while events are
// being dispatched.
func (o *ExportDmabufFrame) handlersForReady() []func(tvSecHi uint32, tvSecLo uint32, tvNsec uint32) {
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	return o.onReady
}

// OnCancel registers a handler for the cancel event.
//
// Handlers are appended, so a second call adds another handler rather than
// replacing the first. Registration is safe while another goroutine dispatches.
func (o *ExportDmabufFrame) OnCancel(handler func(reason uint32)) {
	if handler == nil {
		return
	}
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	o.onCancel = append(o.onCancel, handler)
}

// handlersForCancel returns the handlers registered for cancel, taken
// under the lock so a handler may register another handler while events are
// being dispatched.
func (o *ExportDmabufFrame) handlersForCancel() []func(reason uint32) {
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	return o.onCancel
}

// EventSignature returns the declared event argument types in wire order.
func (o *ExportDmabufFrame) EventSignature(opcode uint16) (string, bool) {
	switch opcode {
	case 0:
		return "uint,uint,uint,uint,uint,uint,uint,uint,uint,uint,", true
	case 1:
		return "uint,fd,uint,uint,uint,uint,", true
	case 2:
		return "uint,uint,uint,", true
	case 3:
		return "uint,", true
	default:
		return "", false
	}
}

// Dispatch decodes one event on zwlr_export_dmabuf_frame_v1 and calls the registered handlers.
func (o *ExportDmabufFrame) Dispatch(event *wl.Event) {
	switch event.Opcode {
	case 0: // frame
		width := event.Uint32()
		height := event.Uint32()
		offsetX := event.Uint32()
		offsetY := event.Uint32()
		bufferFlags := event.Uint32()
		flags := event.Uint32()
		format := event.Uint32()
		modHigh := event.Uint32()
		modLow := event.Uint32()
		numObjects := event.Uint32()

		for i, handler := range o.handlersForFrame() {
			_ = i
			handler(width, height, offsetX, offsetY, bufferFlags, flags, format, modHigh, modLow, numObjects)
		}
	case 1: // object
		index := event.Uint32()
		fd := event.FD()
		size := event.Uint32()
		offset := event.Uint32()
		stride := event.Uint32()
		planeIndex := event.Uint32()
		ownedfd := fd
		defer ownedfd.Close()

		for i, handler := range o.handlersForObject() {
			if i > 0 {
				fd = nil
			}
			handler(index, fd, size, offset, stride, planeIndex)
		}
	case 2: // ready
		tvSecHi := event.Uint32()
		tvSecLo := event.Uint32()
		tvNsec := event.Uint32()

		for i, handler := range o.handlersForReady() {
			_ = i
			handler(tvSecHi, tvSecLo, tvNsec)
		}
	case 3: // cancel
		reason := event.Uint32()

		for i, handler := range o.handlersForCancel() {
			_ = i
			handler(reason)
		}
	default:
	}
}
