// Code generated by wlbgen; DO NOT EDIT.
package wlrexportdmabuf

import (
	"fmt"
	wayland "github.com/bnema/go-wayland-bindings/server/wayland"
	"github.com/bnema/purego-libwayland/server"
)

var ZwlrExportDmabufManagerV1Interface *server.Interface
var ZwlrExportDmabufFrameV1Interface *server.Interface

func init() {
	ZwlrExportDmabufManagerV1Interface = &server.Interface{Name: "zwlr_export_dmabuf_manager_v1", Version: 1}
	ZwlrExportDmabufFrameV1Interface = &server.Interface{Name: "zwlr_export_dmabuf_frame_v1", Version: 1}
	ZwlrExportDmabufManagerV1Interface.Requests = []server.Message{
		{Name: "capture_output", Signature: "nio", Types: []*server.Interface{ZwlrExportDmabufFrameV1Interface, nil, wayland.OutputInterface}},
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
	}
	ZwlrExportDmabufManagerV1Interface.Events = []server.Message{}
	ZwlrExportDmabufFrameV1Interface.Requests = []server.Message{
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
	}
	ZwlrExportDmabufFrameV1Interface.Events = []server.Message{
		{Name: "frame", Signature: "uuuuuuuuuu", Types: []*server.Interface{nil, nil, nil, nil, nil, nil, nil, nil, nil, nil}},
		{Name: "object", Signature: "uhuuuu", Types: []*server.Interface{nil, nil, nil, nil, nil, nil}},
		{Name: "ready", Signature: "uuu", Types: []*server.Interface{nil, nil, nil}},
		{Name: "cancel", Signature: "u", Types: []*server.Interface{nil}},
	}
	if err := server.NewInterfaces(ZwlrExportDmabufManagerV1Interface, ZwlrExportDmabufFrameV1Interface); err != nil {
		panic(err)
	}
}

// ZwlrExportDmabufManagerV1 manager to inform clients and begin capturing.
type ZwlrExportDmabufManagerV1 struct{ *server.Resource }

func WrapZwlrExportDmabufManagerV1(r *server.Resource) *ZwlrExportDmabufManagerV1 {
	if r == nil {
		return nil
	}
	return &ZwlrExportDmabufManagerV1{r}
}

const ZwlrExportDmabufManagerV1RequestCaptureOutput uint32 = 0
const ZwlrExportDmabufManagerV1RequestDestroy uint32 = 1

// ZwlrExportDmabufManagerV1Handler handles zwlr_export_dmabuf_manager_v1 requests.
type ZwlrExportDmabufManagerV1Handler interface {
	CaptureOutput(self *ZwlrExportDmabufManagerV1, frame uint32, overlayCursor int32, output *wayland.Output)
	Destroy(self *ZwlrExportDmabufManagerV1)
}

func NewZwlrExportDmabufManagerV1(c server.Client, version int32, id uint32, h ZwlrExportDmabufManagerV1Handler) (*ZwlrExportDmabufManagerV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for zwlr_export_dmabuf_manager_v1")
	}
	var self *ZwlrExportDmabufManagerV1
	r, err := c.CreateResource(ZwlrExportDmabufManagerV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.CaptureOutput(self, args[0].NewID(), args[1].Int(), wayland.WrapOutput(args[2].Resource()))
		case 1:
			h.Destroy(self)
			self.Destroy()
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapZwlrExportDmabufManagerV1(r)
	r.Data = self
	return self, nil
}
func NewZwlrExportDmabufManagerV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(ZwlrExportDmabufManagerV1Interface, version, bind)
}

// ZwlrExportDmabufFrameV1 a DMA-BUF frame.
type ZwlrExportDmabufFrameV1 struct{ *server.Resource }

func WrapZwlrExportDmabufFrameV1(r *server.Resource) *ZwlrExportDmabufFrameV1 {
	if r == nil {
		return nil
	}
	return &ZwlrExportDmabufFrameV1{r}
}

const ZwlrExportDmabufFrameV1RequestDestroy uint32 = 0
const ZwlrExportDmabufFrameV1EventFrame uint32 = 0
const ZwlrExportDmabufFrameV1EventObject uint32 = 1
const ZwlrExportDmabufFrameV1EventReady uint32 = 2
const ZwlrExportDmabufFrameV1EventCancel uint32 = 3

// ZwlrExportDmabufFrameV1Flags frame flags.
type ZwlrExportDmabufFrameV1Flags uint32

const (
	ZwlrExportDmabufFrameV1FlagsTransient ZwlrExportDmabufFrameV1Flags = 0x1
)

// ZwlrExportDmabufFrameV1CancelReason cancel reason.
type ZwlrExportDmabufFrameV1CancelReason uint32

const (
	ZwlrExportDmabufFrameV1CancelReasonTemporary ZwlrExportDmabufFrameV1CancelReason = 0
	ZwlrExportDmabufFrameV1CancelReasonPermanent ZwlrExportDmabufFrameV1CancelReason = 1
	ZwlrExportDmabufFrameV1CancelReasonResizing  ZwlrExportDmabufFrameV1CancelReason = 2
)

// ZwlrExportDmabufFrameV1Handler handles zwlr_export_dmabuf_frame_v1 requests.
type ZwlrExportDmabufFrameV1Handler interface {
	Destroy(self *ZwlrExportDmabufFrameV1)
}

func NewZwlrExportDmabufFrameV1(c server.Client, version int32, id uint32, h ZwlrExportDmabufFrameV1Handler) (*ZwlrExportDmabufFrameV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for zwlr_export_dmabuf_frame_v1")
	}
	var self *ZwlrExportDmabufFrameV1
	r, err := c.CreateResource(ZwlrExportDmabufFrameV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Destroy(self)
			self.Destroy()
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapZwlrExportDmabufFrameV1(r)
	r.Data = self
	return self, nil
}

// SendFrame a frame description.
func (self *ZwlrExportDmabufFrameV1) SendFrame(width uint32, height uint32, offsetX uint32, offsetY uint32, bufferFlags uint32, flags uint32, format uint32, modHigh uint32, modLow uint32, numObjects uint32) {
	self.PostEvent(ZwlrExportDmabufFrameV1EventFrame, server.Uint(width), server.Uint(height), server.Uint(offsetX), server.Uint(offsetY), server.Uint(bufferFlags), server.Uint(flags), server.Uint(format), server.Uint(modHigh), server.Uint(modLow), server.Uint(numObjects))
}

// SendObject an object description.
func (self *ZwlrExportDmabufFrameV1) SendObject(index uint32, fd int, size uint32, offset uint32, stride uint32, planeIndex uint32) {
	self.PostEvent(ZwlrExportDmabufFrameV1EventObject, server.Uint(index), server.Fd(fd), server.Uint(size), server.Uint(offset), server.Uint(stride), server.Uint(planeIndex))
}

// SendReady indicates frame is available for reading.
func (self *ZwlrExportDmabufFrameV1) SendReady(tvSecHi uint32, tvSecLo uint32, tvNsec uint32) {
	self.PostEvent(ZwlrExportDmabufFrameV1EventReady, server.Uint(tvSecHi), server.Uint(tvSecLo), server.Uint(tvNsec))
}

// SendCancel indicates the frame is no longer valid.
func (self *ZwlrExportDmabufFrameV1) SendCancel(reason uint32) {
	self.PostEvent(ZwlrExportDmabufFrameV1EventCancel, server.Uint(reason))
}
func NewZwlrExportDmabufFrameV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(ZwlrExportDmabufFrameV1Interface, version, bind)
}
func resourceOf(v interface{ GetResource() *server.Resource }) *server.Resource {
	if v == nil {
		return nil
	}
	return v.GetResource()
}
func (self *ZwlrExportDmabufManagerV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *ZwlrExportDmabufFrameV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
