package server_test

// Importing every generated package runs its init, which builds the
// libwayland interface tables and panics on any inconsistency.
import (
	"testing"

	_ "github.com/bnema/go-wayland-bindings/server/alphamodifier"
	_ "github.com/bnema/go-wayland-bindings/server/colormanagement"
	_ "github.com/bnema/go-wayland-bindings/server/colorrepresentation"
	_ "github.com/bnema/go-wayland-bindings/server/committiming"
	_ "github.com/bnema/go-wayland-bindings/server/contenttype"
	_ "github.com/bnema/go-wayland-bindings/server/cursorshape"
	_ "github.com/bnema/go-wayland-bindings/server/drmlease"
	_ "github.com/bnema/go-wayland-bindings/server/extbackgroundeffect"
	_ "github.com/bnema/go-wayland-bindings/server/extdatacontrol"
	_ "github.com/bnema/go-wayland-bindings/server/extforeigntoplevellist"
	_ "github.com/bnema/go-wayland-bindings/server/extidlenotify"
	_ "github.com/bnema/go-wayland-bindings/server/extimagecapturesource"
	_ "github.com/bnema/go-wayland-bindings/server/extimagecopycapture"
	_ "github.com/bnema/go-wayland-bindings/server/extsessionlock"
	_ "github.com/bnema/go-wayland-bindings/server/exttransientseat"
	_ "github.com/bnema/go-wayland-bindings/server/extworkspace"
	_ "github.com/bnema/go-wayland-bindings/server/fifo"
	_ "github.com/bnema/go-wayland-bindings/server/fractionalscale"
	_ "github.com/bnema/go-wayland-bindings/server/fullscreenshell"
	_ "github.com/bnema/go-wayland-bindings/server/idleinhibit"
	_ "github.com/bnema/go-wayland-bindings/server/inputmethod"
	_ "github.com/bnema/go-wayland-bindings/server/inputtimestamps"
	_ "github.com/bnema/go-wayland-bindings/server/keyboardshortcutsinhibit"
	_ "github.com/bnema/go-wayland-bindings/server/linuxdmabuf"
	_ "github.com/bnema/go-wayland-bindings/server/linuxdrmsyncobj"
	_ "github.com/bnema/go-wayland-bindings/server/linuxexplicitsynchronization"
	_ "github.com/bnema/go-wayland-bindings/server/pointerconstraints"
	_ "github.com/bnema/go-wayland-bindings/server/pointergestures"
	_ "github.com/bnema/go-wayland-bindings/server/pointerwarp"
	_ "github.com/bnema/go-wayland-bindings/server/presentationtime"
	_ "github.com/bnema/go-wayland-bindings/server/primaryselection"
	_ "github.com/bnema/go-wayland-bindings/server/relativepointer"
	_ "github.com/bnema/go-wayland-bindings/server/securitycontext"
	_ "github.com/bnema/go-wayland-bindings/server/serverdecoration"
	_ "github.com/bnema/go-wayland-bindings/server/singlepixelbuffer"
	_ "github.com/bnema/go-wayland-bindings/server/tablet"
	_ "github.com/bnema/go-wayland-bindings/server/tearingcontrol"
	_ "github.com/bnema/go-wayland-bindings/server/textinput"
	_ "github.com/bnema/go-wayland-bindings/server/viewporter"
	_ "github.com/bnema/go-wayland-bindings/server/virtualkeyboard"
	_ "github.com/bnema/go-wayland-bindings/server/wayland"
	_ "github.com/bnema/go-wayland-bindings/server/wlrdatacontrol"
	_ "github.com/bnema/go-wayland-bindings/server/wlrexportdmabuf"
	_ "github.com/bnema/go-wayland-bindings/server/wlrforeigntoplevelmanagement"
	_ "github.com/bnema/go-wayland-bindings/server/wlrgammacontrol"
	_ "github.com/bnema/go-wayland-bindings/server/wlrinputinhibitor"
	_ "github.com/bnema/go-wayland-bindings/server/wlrlayershell"
	_ "github.com/bnema/go-wayland-bindings/server/wlroutputmanagement"
	_ "github.com/bnema/go-wayland-bindings/server/wlroutputpowermanagement"
	_ "github.com/bnema/go-wayland-bindings/server/wlrscreencopy"
	_ "github.com/bnema/go-wayland-bindings/server/wlrvirtualpointer"
	_ "github.com/bnema/go-wayland-bindings/server/xdgactivation"
	_ "github.com/bnema/go-wayland-bindings/server/xdgdecoration"
	_ "github.com/bnema/go-wayland-bindings/server/xdgdialog"
	_ "github.com/bnema/go-wayland-bindings/server/xdgforeign"
	_ "github.com/bnema/go-wayland-bindings/server/xdgoutput"
	_ "github.com/bnema/go-wayland-bindings/server/xdgsessionmanagement"
	_ "github.com/bnema/go-wayland-bindings/server/xdgshell"
	_ "github.com/bnema/go-wayland-bindings/server/xdgsystembell"
	_ "github.com/bnema/go-wayland-bindings/server/xdgtopleveldrag"
	_ "github.com/bnema/go-wayland-bindings/server/xdgtoplevelicon"
	_ "github.com/bnema/go-wayland-bindings/server/xdgtopleveltag"
	_ "github.com/bnema/go-wayland-bindings/server/xwaylandkeyboardgrab"
	_ "github.com/bnema/go-wayland-bindings/server/xwaylandshell"
)

func TestGeneratedPackagesInit(t *testing.T) {}
