// Code generated by wlbgen. DO NOT EDIT.
// Protocol: wlr_gamma_control_unstable_v1
// Source: wlr-gamma-control-unstable-v1.xml

// Upstream protocol copyright and license:
// Copyright © 2015 Giulio camuffo
// Copyright © 2018 Simon Ser
//
// Permission to use, copy, modify, distribute, and sell this
// software and its documentation for any purpose is hereby granted
// without fee, provided that the above copyright notice appear in
// all copies and that both that copyright notice and this permission
// notice appear in supporting documentation, and that the name of
// the copyright holders not be used in advertising or publicity
// pertaining to distribution of the software without specific,
// written prior permission.  The copyright holders make no
// representations about the suitability of this software for any
// purpose.  It is provided "as is" without express or implied
// warranty.
//
// THE COPYRIGHT HOLDERS DISCLAIM ALL WARRANTIES WITH REGARD TO THIS
// SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
// FITNESS, IN NO EVENT SHALL THE COPYRIGHT HOLDERS BE LIABLE FOR ANY
// SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
// AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
// ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
// THIS SOFTWARE.

package wlrgammacontrol

import (
	"sync"

	cross_wl_output "github.com/bnema/go-wayland-bindings/client/wayland"
	"github.com/bnema/wlturbo/wl"
)

// ERROR_INVALID_GAMMA is the error invalid_gamma value.
const ERROR_INVALID_GAMMA = 1

// GammaControlManagerInterface is the protocol interface name.
const GammaControlManagerInterface = "zwlr_gamma_control_manager_v1"

// GammaControlManager is the generated binding for zwlr_gamma_control_manager_v1 version 1.
type GammaControlManager struct {
	wl.BaseProxy
}

// NewGammaControlManager returns an unbound GammaControlManager.
func NewGammaControlManager(ctx *wl.Context) *GammaControlManager {
	obj := &GammaControlManager{}
	obj.SetContext(ctx)
	ctx.Register(obj)
	return obj
}

// Create a gamma control that can be used to adjust gamma tables for the provided output.
func (o *GammaControlManager) GetGammaControl(output *cross_wl_output.Output) (*GammaControl, error) {
	var arg1 wl.Object
	if output != nil {
		arg1 = output
	}
	child := &GammaControl{}
	child.SetContext(o.Context())
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 0, Name: "zwlr_gamma_control_manager_v1.get_gamma_control", Child: child}, wl.ArgObject(child), wl.ArgObject(arg1)); err != nil {
		return nil, err
	}
	return child, nil
}

// All objects created by the manager will still remain valid, until their appropriate destroy request has been called.
func (o *GammaControlManager) Destroy() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 1, Name: "zwlr_gamma_control_manager_v1.destroy", Destructor: true}); err != nil {
		return err
	}
	return nil
}

// EventSignature returns the declared event argument types in wire order.
func (o *GammaControlManager) EventSignature(opcode uint16) (string, bool) {
	switch opcode {
	default:
		return "", false
	}
}

// Dispatch decodes one event on zwlr_gamma_control_manager_v1 and calls the registered handlers.
func (o *GammaControlManager) Dispatch(event *wl.Event) {
	switch event.Opcode {
	default:
	}
}

// GammaControlInterface is the protocol interface name.
const GammaControlInterface = "zwlr_gamma_control_v1"

// GammaControl is the generated binding for zwlr_gamma_control_v1 version 1.
type GammaControl struct {
	wl.BaseProxy
	// handlersMu guards the handler slices: a client may register or replace
	// handlers while another goroutine dispatches events.
	handlersMu  sync.Mutex
	onGammaSize []func(size uint32)
	onFailed    []func()
}

// NewGammaControl returns an unbound GammaControl.
func NewGammaControl(ctx *wl.Context) *GammaControl {
	obj := &GammaControl{}
	obj.SetContext(ctx)
	ctx.Register(obj)
	return obj
}

// Set the gamma table. The file descriptor can be memory-mapped to provide the raw gamma table, which contains successive gamma ramps for the red, green and blue channels. Each gamma ramp is an array of 16-byte unsigned integers which has the same length as the gamma size. The file descriptor data must have the same length as three times the gamma size.
func (o *GammaControl) SetGamma(fd int) error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 0, Name: "zwlr_gamma_control_v1.set_gamma", FDs: []int{fd}}, wl.ArgFD()); err != nil {
		return err
	}
	return nil
}

// Destroys the gamma control object. If the object is still valid, this restores the original gamma tables.
func (o *GammaControl) Destroy() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 1, Name: "zwlr_gamma_control_v1.destroy", Destructor: true}); err != nil {
		return err
	}
	return nil
}

// OnGammaSize registers a handler for the gamma_size event.
//
// Handlers are appended, so a second call adds another handler rather than
// replacing the first. Registration is safe while another goroutine dispatches.
func (o *GammaControl) OnGammaSize(handler func(size uint32)) {
	if handler == nil {
		return
	}
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	o.onGammaSize = append(o.onGammaSize, handler)
}

// handlersForGammaSize returns the handlers registered for gamma_size, taken
// under the lock so a handler may register another handler while events are
// being dispatched.
func (o *GammaControl) handlersForGammaSize() []func(size uint32) {
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	return o.onGammaSize
}

// OnFailed registers a handler for the failed event.
//
// Handlers are appended, so a second call adds another handler rather than
// replacing the first. Registration is safe while another goroutine dispatches.
func (o *GammaControl) OnFailed(handler func()) {
	if handler == nil {
		return
	}
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	o.onFailed = append(o.onFailed, handler)
}

// handlersForFailed returns the handlers registered for failed, taken
// under the lock so a handler may register another handler while events are
// being dispatched.
func (o *GammaControl) handlersForFailed() []func() {
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	return o.onFailed
}

// EventSignature returns the declared event argument types in wire order.
func (o *GammaControl) EventSignature(opcode uint16) (string, bool) {
	switch opcode {
	case 0:
		return "uint,", true
	case 1:
		return "", true
	default:
		return "", false
	}
}

// Dispatch decodes one event on zwlr_gamma_control_v1 and calls the registered handlers.
func (o *GammaControl) Dispatch(event *wl.Event) {
	switch event.Opcode {
	case 0: // gamma_size
		size := event.Uint32()

		for i, handler := range o.handlersForGammaSize() {
			_ = i
			handler(size)
		}
	case 1: // failed

		for i, handler := range o.handlersForFailed() {
			_ = i
			handler()
		}
	default:
	}
}
