// Code generated by wlbgen. DO NOT EDIT.
// Protocol: xdg_toplevel_drag_v1
// Source: xdg-toplevel-drag-v1.xml

// Upstream protocol copyright and license:
// Copyright 2023 David Redondo
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package xdgtopleveldrag

import (
	cross_wl_data_source "github.com/bnema/go-wayland-bindings/client/wayland"
	cross_xdg_toplevel "github.com/bnema/go-wayland-bindings/client/xdgshell"
	"github.com/bnema/wlturbo/wl"
)

// ERROR_INVALID_SOURCE is the error invalid_source value.
const ERROR_INVALID_SOURCE = 0

// ERROR_TOPLEVEL_ATTACHED is the error toplevel_attached value.
const ERROR_TOPLEVEL_ATTACHED = 0

// ERROR_ONGOING_DRAG is the error ongoing_drag value.
const ERROR_ONGOING_DRAG = 1

// XdgToplevelDragManagerInterface is the protocol interface name.
const XdgToplevelDragManagerInterface = "xdg_toplevel_drag_manager_v1"

// XdgToplevelDragManager is the generated binding for xdg_toplevel_drag_manager_v1 version 1.
type XdgToplevelDragManager struct {
	wl.BaseProxy
}

// NewXdgToplevelDragManager returns an unbound XdgToplevelDragManager.
func NewXdgToplevelDragManager(ctx *wl.Context) *XdgToplevelDragManager {
	obj := &XdgToplevelDragManager{}
	obj.SetContext(ctx)
	ctx.Register(obj)
	return obj
}

// Destroy this xdg_toplevel_drag_manager_v1 object. Other objects, including xdg_toplevel_drag_v1 objects created by this factory, are not affected by this request.
func (o *XdgToplevelDragManager) Destroy() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 0, Name: "xdg_toplevel_drag_manager_v1.destroy", Destructor: true}); err != nil {
		return err
	}
	return nil
}

// Create an xdg_toplevel_drag for a drag and drop operation that is going to be started with data_source. This request can only be made on sources used in drag-and-drop, so it must be performed before wl_data_device.start_drag. Attempting to use the source other than for drag-and-drop such as in wl_data_device.set_selection will raise an invalid_source error. Destroying data_source while a toplevel is attached to the xdg_toplevel_drag is undefined.
func (o *XdgToplevelDragManager) GetXdgToplevelDrag(dataSource *cross_wl_data_source.DataSource) (*XdgToplevelDrag, error) {
	var arg1 wl.Object
	if dataSource != nil {
		arg1 = dataSource
	}
	child := &XdgToplevelDrag{}
	child.SetContext(o.Context())
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 1, Name: "xdg_toplevel_drag_manager_v1.get_xdg_toplevel_drag", Child: child}, wl.ArgObject(child), wl.ArgObject(arg1)); err != nil {
		return nil, err
	}
	return child, nil
}

// EventSignature returns the declared event argument types in wire order.
func (o *XdgToplevelDragManager) EventSignature(opcode uint16) (string, bool) {
	switch opcode {
	default:
		return "", false
	}
}

// Dispatch decodes one event on xdg_toplevel_drag_manager_v1 and calls the registered handlers.
func (o *XdgToplevelDragManager) Dispatch(event *wl.Event) {
	switch event.Opcode {
	default:
	}
}

// XdgToplevelDragInterface is the protocol interface name.
const XdgToplevelDragInterface = "xdg_toplevel_drag_v1"

// XdgToplevelDrag is the generated binding for xdg_toplevel_drag_v1 version 1.
type XdgToplevelDrag struct {
	wl.BaseProxy
}

// NewXdgToplevelDrag returns an unbound XdgToplevelDrag.
func NewXdgToplevelDrag(ctx *wl.Context) *XdgToplevelDrag {
	obj := &XdgToplevelDrag{}
	obj.SetContext(ctx)
	ctx.Register(obj)
	return obj
}

// Destroy this xdg_toplevel_drag_v1 object. This request must only be called after the underlying wl_data_source drag has ended, as indicated by the dnd_drop_performed or cancelled events. In any other case an ongoing_drag error is raised.
func (o *XdgToplevelDrag) Destroy() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 0, Name: "xdg_toplevel_drag_v1.destroy", Destructor: true}); err != nil {
		return err
	}
	return nil
}

// Request that the window will be moved with the cursor during the drag operation. The offset is a hint to the compositor how the toplevel should be positioned relative to the cursor hotspot in surface local coordinates and relative to the geometry of the toplevel being attached. See xdg_surface.set_window_geometry. For example it might only be used when an unmapped window is attached. The attached window does not participate in the selection of the drag target. If the toplevel is unmapped while it is attached, it is automatically detached from the drag. In this case this request has to be called again if the window should be attached after it is remapped. This request can be called multiple times but issuing it while a toplevel with an active role is attached raises a toplevel_attached error.
func (o *XdgToplevelDrag) Attach(toplevel *cross_xdg_toplevel.XdgToplevel, xOffset int32, yOffset int32) error {
	var arg0 wl.Object
	if toplevel != nil {
		arg0 = toplevel
	}
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 1, Name: "xdg_toplevel_drag_v1.attach"}, wl.ArgObject(arg0), wl.ArgInt(xOffset), wl.ArgInt(yOffset)); err != nil {
		return err
	}
	return nil
}

// EventSignature returns the declared event argument types in wire order.
func (o *XdgToplevelDrag) EventSignature(opcode uint16) (string, bool) {
	switch opcode {
	default:
		return "", false
	}
}

// Dispatch decodes one event on xdg_toplevel_drag_v1 and calls the registered handlers.
func (o *XdgToplevelDrag) Dispatch(event *wl.Event) {
	switch event.Opcode {
	default:
	}
}
