// Code generated by wlbgen; DO NOT EDIT.
package linuxexplicitsynchronization

import (
	"fmt"
	wayland "github.com/bnema/go-wayland-bindings/server/wayland"
	"github.com/bnema/purego-libwayland/server"
)

var ZwpLinuxExplicitSynchronizationV1Interface *server.Interface
var ZwpLinuxSurfaceSynchronizationV1Interface *server.Interface
var ZwpLinuxBufferReleaseV1Interface *server.Interface

func init() {
	ZwpLinuxExplicitSynchronizationV1Interface = &server.Interface{Name: "zwp_linux_explicit_synchronization_v1", Version: 2}
	ZwpLinuxSurfaceSynchronizationV1Interface = &server.Interface{Name: "zwp_linux_surface_synchronization_v1", Version: 2}
	ZwpLinuxBufferReleaseV1Interface = &server.Interface{Name: "zwp_linux_buffer_release_v1", Version: 1}
	ZwpLinuxExplicitSynchronizationV1Interface.Requests = []server.Message{
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
		{Name: "get_synchronization", Signature: "no", Types: []*server.Interface{ZwpLinuxSurfaceSynchronizationV1Interface, wayland.SurfaceInterface}},
	}
	ZwpLinuxExplicitSynchronizationV1Interface.Events = []server.Message{}
	ZwpLinuxSurfaceSynchronizationV1Interface.Requests = []server.Message{
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
		{Name: "set_acquire_fence", Signature: "h", Types: []*server.Interface{nil}},
		{Name: "get_release", Signature: "n", Types: []*server.Interface{ZwpLinuxBufferReleaseV1Interface}},
	}
	ZwpLinuxSurfaceSynchronizationV1Interface.Events = []server.Message{}
	ZwpLinuxBufferReleaseV1Interface.Requests = []server.Message{}
	ZwpLinuxBufferReleaseV1Interface.Events = []server.Message{
		{Name: "fenced_release", Signature: "h", Types: []*server.Interface{nil}},
		{Name: "immediate_release", Signature: "", Types: []*server.Interface{}},
	}
	if err := server.NewInterfaces(ZwpLinuxExplicitSynchronizationV1Interface, ZwpLinuxSurfaceSynchronizationV1Interface, ZwpLinuxBufferReleaseV1Interface); err != nil {
		panic(err)
	}
}

// ZwpLinuxExplicitSynchronizationV1 protocol for providing explicit synchronization.
type ZwpLinuxExplicitSynchronizationV1 struct{ *server.Resource }

func WrapZwpLinuxExplicitSynchronizationV1(r *server.Resource) *ZwpLinuxExplicitSynchronizationV1 {
	if r == nil {
		return nil
	}
	return &ZwpLinuxExplicitSynchronizationV1{r}
}

const ZwpLinuxExplicitSynchronizationV1RequestDestroy uint32 = 0
const ZwpLinuxExplicitSynchronizationV1RequestGetSynchronization uint32 = 1

// ZwpLinuxExplicitSynchronizationV1Error .
type ZwpLinuxExplicitSynchronizationV1Error uint32

const (
	ZwpLinuxExplicitSynchronizationV1ErrorSynchronizationExists ZwpLinuxExplicitSynchronizationV1Error = 0
)

// ZwpLinuxExplicitSynchronizationV1Handler handles zwp_linux_explicit_synchronization_v1 requests.
type ZwpLinuxExplicitSynchronizationV1Handler interface {
	Destroy(self *ZwpLinuxExplicitSynchronizationV1)
	GetSynchronization(self *ZwpLinuxExplicitSynchronizationV1, id uint32, surface *wayland.Surface)
}

func NewZwpLinuxExplicitSynchronizationV1(c server.Client, version int32, id uint32, h ZwpLinuxExplicitSynchronizationV1Handler) (*ZwpLinuxExplicitSynchronizationV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for zwp_linux_explicit_synchronization_v1")
	}
	var self *ZwpLinuxExplicitSynchronizationV1
	r, err := c.CreateResource(ZwpLinuxExplicitSynchronizationV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Destroy(self)
			self.Destroy()
		case 1:
			h.GetSynchronization(self, args[0].NewID(), wayland.WrapSurface(args[1].Resource()))
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapZwpLinuxExplicitSynchronizationV1(r)
	r.Data = self
	return self, nil
}
func NewZwpLinuxExplicitSynchronizationV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(ZwpLinuxExplicitSynchronizationV1Interface, version, bind)
}

// ZwpLinuxSurfaceSynchronizationV1 per-surface explicit synchronization support.
type ZwpLinuxSurfaceSynchronizationV1 struct{ *server.Resource }

func WrapZwpLinuxSurfaceSynchronizationV1(r *server.Resource) *ZwpLinuxSurfaceSynchronizationV1 {
	if r == nil {
		return nil
	}
	return &ZwpLinuxSurfaceSynchronizationV1{r}
}

const ZwpLinuxSurfaceSynchronizationV1RequestDestroy uint32 = 0
const ZwpLinuxSurfaceSynchronizationV1RequestSetAcquireFence uint32 = 1
const ZwpLinuxSurfaceSynchronizationV1RequestGetRelease uint32 = 2

// ZwpLinuxSurfaceSynchronizationV1Error .
type ZwpLinuxSurfaceSynchronizationV1Error uint32

const (
	ZwpLinuxSurfaceSynchronizationV1ErrorInvalidFence      ZwpLinuxSurfaceSynchronizationV1Error = 0
	ZwpLinuxSurfaceSynchronizationV1ErrorDuplicateFence    ZwpLinuxSurfaceSynchronizationV1Error = 1
	ZwpLinuxSurfaceSynchronizationV1ErrorDuplicateRelease  ZwpLinuxSurfaceSynchronizationV1Error = 2
	ZwpLinuxSurfaceSynchronizationV1ErrorNoSurface         ZwpLinuxSurfaceSynchronizationV1Error = 3
	ZwpLinuxSurfaceSynchronizationV1ErrorUnsupportedBuffer ZwpLinuxSurfaceSynchronizationV1Error = 4
	ZwpLinuxSurfaceSynchronizationV1ErrorNoBuffer          ZwpLinuxSurfaceSynchronizationV1Error = 5
)

// ZwpLinuxSurfaceSynchronizationV1Handler handles zwp_linux_surface_synchronization_v1 requests.
type ZwpLinuxSurfaceSynchronizationV1Handler interface {
	Destroy(self *ZwpLinuxSurfaceSynchronizationV1)
	SetAcquireFence(self *ZwpLinuxSurfaceSynchronizationV1, fd int)
	GetRelease(self *ZwpLinuxSurfaceSynchronizationV1, release uint32)
}

func NewZwpLinuxSurfaceSynchronizationV1(c server.Client, version int32, id uint32, h ZwpLinuxSurfaceSynchronizationV1Handler) (*ZwpLinuxSurfaceSynchronizationV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for zwp_linux_surface_synchronization_v1")
	}
	var self *ZwpLinuxSurfaceSynchronizationV1
	r, err := c.CreateResource(ZwpLinuxSurfaceSynchronizationV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Destroy(self)
			self.Destroy()
		case 1:
			h.SetAcquireFence(self, args[0].Fd())
		case 2:
			h.GetRelease(self, args[0].NewID())
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapZwpLinuxSurfaceSynchronizationV1(r)
	r.Data = self
	return self, nil
}
func NewZwpLinuxSurfaceSynchronizationV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(ZwpLinuxSurfaceSynchronizationV1Interface, version, bind)
}

// ZwpLinuxBufferReleaseV1 buffer release explicit synchronization.
type ZwpLinuxBufferReleaseV1 struct{ *server.Resource }

func WrapZwpLinuxBufferReleaseV1(r *server.Resource) *ZwpLinuxBufferReleaseV1 {
	if r == nil {
		return nil
	}
	return &ZwpLinuxBufferReleaseV1{r}
}

const ZwpLinuxBufferReleaseV1EventFencedRelease uint32 = 0
const ZwpLinuxBufferReleaseV1EventImmediateRelease uint32 = 1

// ZwpLinuxBufferReleaseV1Handler handles zwp_linux_buffer_release_v1 requests.
type ZwpLinuxBufferReleaseV1Handler interface {
}

func NewZwpLinuxBufferReleaseV1(c server.Client, version int32, id uint32, h ZwpLinuxBufferReleaseV1Handler) (*ZwpLinuxBufferReleaseV1, error) {
	var self *ZwpLinuxBufferReleaseV1
	r, err := c.CreateResource(ZwpLinuxBufferReleaseV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapZwpLinuxBufferReleaseV1(r)
	r.Data = self
	return self, nil
}

// SendFencedRelease release buffer with fence.
func (self *ZwpLinuxBufferReleaseV1) SendFencedRelease(fence int) {
	self.PostEvent(ZwpLinuxBufferReleaseV1EventFencedRelease, server.Fd(fence))
}

// SendImmediateRelease release buffer immediately.
func (self *ZwpLinuxBufferReleaseV1) SendImmediateRelease() {
	self.PostEvent(ZwpLinuxBufferReleaseV1EventImmediateRelease)
}
func NewZwpLinuxBufferReleaseV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(ZwpLinuxBufferReleaseV1Interface, version, bind)
}
func resourceOf(v interface{ GetResource() *server.Resource }) *server.Resource {
	if v == nil {
		return nil
	}
	return v.GetResource()
}
func (self *ZwpLinuxExplicitSynchronizationV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *ZwpLinuxSurfaceSynchronizationV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *ZwpLinuxBufferReleaseV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
