// Code generated by wlbgen; DO NOT EDIT.

// Upstream protocol copyright and license:
// Copyright (C) 2015 Martin Gräßlin
// Copyright (C) 2015 Marco Martin
// Copyright (C) 2020 Vlad Zahorodnii
// Copyright (C) 2024 Xaver Hugl
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package extbackgroundeffect

import (
	"fmt"
	wayland "github.com/bnema/go-wayland-bindings/server/wayland"
	"github.com/bnema/purego-libwayland/server"
)

var ExtBackgroundEffectManagerV1Interface *server.Interface
var ExtBackgroundEffectSurfaceV1Interface *server.Interface

func init() {
	ExtBackgroundEffectManagerV1Interface = &server.Interface{Name: "ext_background_effect_manager_v1", Version: 1}
	ExtBackgroundEffectSurfaceV1Interface = &server.Interface{Name: "ext_background_effect_surface_v1", Version: 1}
	ExtBackgroundEffectManagerV1Interface.Requests = []server.Message{
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
		{Name: "get_background_effect", Signature: "no", Types: []*server.Interface{ExtBackgroundEffectSurfaceV1Interface, wayland.SurfaceInterface}},
	}
	ExtBackgroundEffectManagerV1Interface.Events = []server.Message{
		{Name: "capabilities", Signature: "u", Types: []*server.Interface{nil}},
	}
	ExtBackgroundEffectSurfaceV1Interface.Requests = []server.Message{
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
		{Name: "set_blur_region", Signature: "?o", Types: []*server.Interface{wayland.RegionInterface}},
	}
	ExtBackgroundEffectSurfaceV1Interface.Events = []server.Message{}
	if err := server.NewInterfaces(ExtBackgroundEffectManagerV1Interface, ExtBackgroundEffectSurfaceV1Interface); err != nil {
		panic(err)
	}
}

// ExtBackgroundEffectManagerV1 background effect factory.
type ExtBackgroundEffectManagerV1 struct{ *server.Resource }

func WrapExtBackgroundEffectManagerV1(r *server.Resource) *ExtBackgroundEffectManagerV1 {
	if r == nil {
		return nil
	}
	return &ExtBackgroundEffectManagerV1{r}
}

const ExtBackgroundEffectManagerV1RequestDestroy uint32 = 0
const ExtBackgroundEffectManagerV1RequestGetBackgroundEffect uint32 = 1
const ExtBackgroundEffectManagerV1EventCapabilities uint32 = 0

// ExtBackgroundEffectManagerV1Error .
type ExtBackgroundEffectManagerV1Error uint32

const (
	ExtBackgroundEffectManagerV1ErrorBackgroundEffectExists ExtBackgroundEffectManagerV1Error = 0
)

// ExtBackgroundEffectManagerV1Capability  (bitfield).
type ExtBackgroundEffectManagerV1Capability uint32

const (
	ExtBackgroundEffectManagerV1CapabilityBlur ExtBackgroundEffectManagerV1Capability = 1
)

// ExtBackgroundEffectManagerV1Handler handles ext_background_effect_manager_v1 requests.
type ExtBackgroundEffectManagerV1Handler interface {
	Destroy(self *ExtBackgroundEffectManagerV1)
	GetBackgroundEffect(self *ExtBackgroundEffectManagerV1, id uint32, surface *wayland.Surface)
}

func NewExtBackgroundEffectManagerV1(c server.Client, version int32, id uint32, h ExtBackgroundEffectManagerV1Handler) (*ExtBackgroundEffectManagerV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for ext_background_effect_manager_v1")
	}
	var self *ExtBackgroundEffectManagerV1
	r, err := c.CreateResource(ExtBackgroundEffectManagerV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Destroy(self)
			self.Destroy()
		case 1:
			h.GetBackgroundEffect(self, args[0].NewID(), wayland.WrapSurface(args[1].Resource()))
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapExtBackgroundEffectManagerV1(r)
	r.Data = self
	return self, nil
}

// SendCapabilities capabilities of the compositor.
func (self *ExtBackgroundEffectManagerV1) SendCapabilities(flags uint32) {
	self.PostEvent(ExtBackgroundEffectManagerV1EventCapabilities, server.Uint(flags))
}
func NewExtBackgroundEffectManagerV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(ExtBackgroundEffectManagerV1Interface, version, bind)
}

// ExtBackgroundEffectSurfaceV1 background effects for a surface.
type ExtBackgroundEffectSurfaceV1 struct{ *server.Resource }

func WrapExtBackgroundEffectSurfaceV1(r *server.Resource) *ExtBackgroundEffectSurfaceV1 {
	if r == nil {
		return nil
	}
	return &ExtBackgroundEffectSurfaceV1{r}
}

const ExtBackgroundEffectSurfaceV1RequestDestroy uint32 = 0
const ExtBackgroundEffectSurfaceV1RequestSetBlurRegion uint32 = 1

// ExtBackgroundEffectSurfaceV1Error .
type ExtBackgroundEffectSurfaceV1Error uint32

const (
	ExtBackgroundEffectSurfaceV1ErrorSurfaceDestroyed ExtBackgroundEffectSurfaceV1Error = 0
)

// ExtBackgroundEffectSurfaceV1Handler handles ext_background_effect_surface_v1 requests.
type ExtBackgroundEffectSurfaceV1Handler interface {
	Destroy(self *ExtBackgroundEffectSurfaceV1)
	SetBlurRegion(self *ExtBackgroundEffectSurfaceV1, region *wayland.Region)
}

func NewExtBackgroundEffectSurfaceV1(c server.Client, version int32, id uint32, h ExtBackgroundEffectSurfaceV1Handler) (*ExtBackgroundEffectSurfaceV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for ext_background_effect_surface_v1")
	}
	var self *ExtBackgroundEffectSurfaceV1
	r, err := c.CreateResource(ExtBackgroundEffectSurfaceV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Destroy(self)
			self.Destroy()
		case 1:
			h.SetBlurRegion(self, wayland.WrapRegion(args[0].Resource()))
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapExtBackgroundEffectSurfaceV1(r)
	r.Data = self
	return self, nil
}
func NewExtBackgroundEffectSurfaceV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(ExtBackgroundEffectSurfaceV1Interface, version, bind)
}
func resourceOf(v interface{ GetResource() *server.Resource }) *server.Resource {
	if v == nil {
		return nil
	}
	return v.GetResource()
}
func (self *ExtBackgroundEffectManagerV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *ExtBackgroundEffectSurfaceV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
