// Code generated by wlbgen. DO NOT EDIT.
// Protocol: xdg_toplevel_icon_v1
// Source: xdg-toplevel-icon-v1.xml

// Upstream protocol copyright and license:
// Copyright © 2023-2024 Matthias Klumpp
// Copyright ©      2024 David Edmundson
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package xdgtoplevelicon

import (
	"sync"

	cross_wl_buffer "github.com/bnema/go-wayland-bindings/client/wayland"
	cross_xdg_toplevel "github.com/bnema/go-wayland-bindings/client/xdgshell"
	"github.com/bnema/wlturbo/wl"
)

// ERROR_INVALID_BUFFER is the error invalid_buffer value.
const ERROR_INVALID_BUFFER = 1

// ERROR_IMMUTABLE is the error immutable value.
const ERROR_IMMUTABLE = 2

// ERROR_NO_BUFFER is the error no_buffer value.
const ERROR_NO_BUFFER = 3

// XdgToplevelIconManagerInterface is the protocol interface name.
const XdgToplevelIconManagerInterface = "xdg_toplevel_icon_manager_v1"

// XdgToplevelIconManager is the generated binding for xdg_toplevel_icon_manager_v1 version 1.
type XdgToplevelIconManager struct {
	wl.BaseProxy
	// handlersMu guards the handler slices: a client may register or replace
	// handlers while another goroutine dispatches events.
	handlersMu sync.Mutex
	onIconSize []func(size int32)
	onDone     []func()
}

// NewXdgToplevelIconManager returns an unbound XdgToplevelIconManager.
func NewXdgToplevelIconManager(ctx *wl.Context) *XdgToplevelIconManager {
	obj := &XdgToplevelIconManager{}
	obj.SetContext(ctx)
	ctx.Register(obj)
	return obj
}

// Destroy the toplevel icon manager. This does not destroy objects created with the manager.
func (o *XdgToplevelIconManager) Destroy() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 0, Name: "xdg_toplevel_icon_manager_v1.destroy", Destructor: true}); err != nil {
		return err
	}
	return nil
}

// Creates a new icon object. This icon can then be attached to a xdg_toplevel via the 'set_icon' request.
func (o *XdgToplevelIconManager) CreateIcon() (*XdgToplevelIcon, error) {
	child := &XdgToplevelIcon{}
	child.SetContext(o.Context())
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 1, Name: "xdg_toplevel_icon_manager_v1.create_icon", Child: child}, wl.ArgObject(child)); err != nil {
		return nil, err
	}
	return child, nil
}

// This request assigns the icon 'icon' to 'toplevel', or clears the toplevel icon if 'icon' was null. This state is double-buffered and is applied on the next wl_surface.commit of the toplevel. After making this call, the xdg_toplevel_icon_v1 provided as 'icon' can be destroyed by the client without 'toplevel' losing its icon. The xdg_toplevel_icon_v1 is immutable from this point, and any future attempts to change it must raise the 'xdg_toplevel_icon_v1.immutable' protocol error. The compositor must set the toplevel icon from either the pixel data the icon provides, or by loading a stock icon using the icon name. See the description of 'xdg_toplevel_icon_v1' for details. If 'icon' is set to null, the icon of the respective toplevel is reset to its default icon (usually the icon of the application, derived from its desktop-entry file, or a placeholder icon). If this request is passed an icon with no pixel buffers or icon name assigned, the icon must be reset just like if 'icon' was null.
func (o *XdgToplevelIconManager) SetIcon(toplevel *cross_xdg_toplevel.XdgToplevel, icon *XdgToplevelIcon) error {
	var arg0 wl.Object
	if toplevel != nil {
		arg0 = toplevel
	}
	var arg1 wl.Object
	if icon != nil {
		arg1 = icon
	}
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 2, Name: "xdg_toplevel_icon_manager_v1.set_icon"}, wl.ArgObject(arg0), wl.ArgObject(arg1)); err != nil {
		return err
	}
	return nil
}

// OnIconSize registers a handler for the icon_size event.
//
// Handlers are appended, so a second call adds another handler rather than
// replacing the first. Registration is safe while another goroutine dispatches.
func (o *XdgToplevelIconManager) OnIconSize(handler func(size int32)) {
	if handler == nil {
		return
	}
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	o.onIconSize = append(o.onIconSize, handler)
}

// handlersForIconSize returns the handlers registered for icon_size, taken
// under the lock so a handler may register another handler while events are
// being dispatched.
func (o *XdgToplevelIconManager) handlersForIconSize() []func(size int32) {
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	return o.onIconSize
}

// OnDone registers a handler for the done event.
//
// Handlers are appended, so a second call adds another handler rather than
// replacing the first. Registration is safe while another goroutine dispatches.
func (o *XdgToplevelIconManager) OnDone(handler func()) {
	if handler == nil {
		return
	}
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	o.onDone = append(o.onDone, handler)
}

// handlersForDone returns the handlers registered for done, taken
// under the lock so a handler may register another handler while events are
// being dispatched.
func (o *XdgToplevelIconManager) handlersForDone() []func() {
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	return o.onDone
}

// EventSignature returns the declared event argument types in wire order.
func (o *XdgToplevelIconManager) EventSignature(opcode uint16) (string, bool) {
	switch opcode {
	case 0:
		return "int,", true
	case 1:
		return "", true
	default:
		return "", false
	}
}

// Dispatch decodes one event on xdg_toplevel_icon_manager_v1 and calls the registered handlers.
func (o *XdgToplevelIconManager) Dispatch(event *wl.Event) {
	switch event.Opcode {
	case 0: // icon_size
		size := event.Int32()

		for i, handler := range o.handlersForIconSize() {
			_ = i
			handler(size)
		}
	case 1: // done

		for i, handler := range o.handlersForDone() {
			_ = i
			handler()
		}
	default:
	}
}

// XdgToplevelIconInterface is the protocol interface name.
const XdgToplevelIconInterface = "xdg_toplevel_icon_v1"

// XdgToplevelIcon is the generated binding for xdg_toplevel_icon_v1 version 1.
type XdgToplevelIcon struct {
	wl.BaseProxy
}

// NewXdgToplevelIcon returns an unbound XdgToplevelIcon.
func NewXdgToplevelIcon(ctx *wl.Context) *XdgToplevelIcon {
	obj := &XdgToplevelIcon{}
	obj.SetContext(ctx)
	ctx.Register(obj)
	return obj
}

// Destroys the 'xdg_toplevel_icon_v1' object. The icon must still remain set on every toplevel it was assigned to, until the toplevel icon is reset explicitly.
func (o *XdgToplevelIcon) Destroy() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 0, Name: "xdg_toplevel_icon_v1.destroy", Destructor: true}); err != nil {
		return err
	}
	return nil
}

// This request assigns an icon name to this icon. Any previously set name is overridden. The compositor must resolve 'icon_name' according to the lookup rules described in the XDG icon theme specification[1] using the environment's current icon theme. If the compositor does not support icon names or cannot resolve 'icon_name' according to the XDG icon theme specification it must fall back to using pixel buffer data instead. If this request is made after the icon has been assigned to a toplevel via 'set_icon', an 'immutable' error must be raised. [1]: https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html
func (o *XdgToplevelIcon) SetName(iconName string) error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 1, Name: "xdg_toplevel_icon_v1.set_name"}, wl.ArgString(iconName)); err != nil {
		return err
	}
	return nil
}

// This request adds pixel data supplied as wl_buffer to the icon. The client should add pixel data for all icon sizes and scales that it can provide, or which are explicitly requested by the compositor via 'icon_size' events on xdg_toplevel_icon_manager_v1. The wl_buffer supplying pixel data as 'buffer' must be backed by wl_shm and must be a square (width and height being equal). If any of these buffer requirements are not fulfilled, a 'invalid_buffer' error must be raised. If this icon instance already has a buffer of the same size and scale from a previous 'add_buffer' request, data from the last request overrides the preexisting pixel data. The wl_buffer must be kept alive for as long as the xdg_toplevel_icon it is associated with is not destroyed, otherwise a 'no_buffer' error is raised. The buffer contents must not be modified after it was assigned to the icon. As a result, the region of the wl_shm_pool's backing storage used for the wl_buffer must not be modified after this request is sent. The wl_buffer.release event is unused. If this request is made after the icon has been assigned to a toplevel via 'set_icon', an 'immutable' error must be raised.
func (o *XdgToplevelIcon) AddBuffer(buffer *cross_wl_buffer.Buffer, scale int32) error {
	var arg0 wl.Object
	if buffer != nil {
		arg0 = buffer
	}
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 2, Name: "xdg_toplevel_icon_v1.add_buffer"}, wl.ArgObject(arg0), wl.ArgInt(scale)); err != nil {
		return err
	}
	return nil
}

// EventSignature returns the declared event argument types in wire order.
func (o *XdgToplevelIcon) EventSignature(opcode uint16) (string, bool) {
	switch opcode {
	default:
		return "", false
	}
}

// Dispatch decodes one event on xdg_toplevel_icon_v1 and calls the registered handlers.
func (o *XdgToplevelIcon) Dispatch(event *wl.Event) {
	switch event.Opcode {
	default:
	}
}
