// Code generated by wlbgen. DO NOT EDIT.
// Protocol: security_context_v1
// Source: security-context-v1.xml

// Upstream protocol copyright and license:
// Copyright © 2021 Simon Ser
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package securitycontext

import (
	"github.com/bnema/wlturbo/wl"
)

// ERROR_INVALID_LISTEN_FD is the error invalid_listen_fd value.
const ERROR_INVALID_LISTEN_FD = 1

// ERROR_NESTED is the error nested value.
const ERROR_NESTED = 2

// ERROR_ALREADY_USED is the error already_used value.
const ERROR_ALREADY_USED = 1

// ERROR_ALREADY_SET is the error already_set value.
const ERROR_ALREADY_SET = 2

// ERROR_INVALID_METADATA is the error invalid_metadata value.
const ERROR_INVALID_METADATA = 3

// WpSecurityContextManagerInterface is the protocol interface name.
const WpSecurityContextManagerInterface = "wp_security_context_manager_v1"

// WpSecurityContextManager is the generated binding for wp_security_context_manager_v1 version 1.
type WpSecurityContextManager struct {
	wl.BaseProxy
}

// NewWpSecurityContextManager returns an unbound WpSecurityContextManager.
func NewWpSecurityContextManager(ctx *wl.Context) *WpSecurityContextManager {
	obj := &WpSecurityContextManager{}
	obj.SetContext(ctx)
	ctx.Register(obj)
	return obj
}

// Destroy the manager. This doesn't destroy objects created with the manager.
func (o *WpSecurityContextManager) Destroy() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 0, Name: "wp_security_context_manager_v1.destroy", Destructor: true}); err != nil {
		return err
	}
	return nil
}

// Creates a new security context with a socket listening FD. The compositor will accept new client connections on listen_fd. listen_fd must be ready to accept new connections when this request is sent by the client. In other words, the client must call bind(2) and listen(2) before sending the FD. close_fd is a FD that will signal hangup when the compositor should stop accepting new connections on listen_fd. The compositor must continue to accept connections on listen_fd when the Wayland client which created the security context disconnects. After sending this request, closing listen_fd and close_fd remains the only valid operation on them.
func (o *WpSecurityContextManager) CreateListener(listenFd int, closeFd int) (*WpSecurityContext, error) {
	child := &WpSecurityContext{}
	child.SetContext(o.Context())
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 1, Name: "wp_security_context_manager_v1.create_listener", Child: child, FDs: []int{listenFd, closeFd}}, wl.ArgObject(child), wl.ArgFD(), wl.ArgFD()); err != nil {
		return nil, err
	}
	return child, nil
}

// EventSignature returns the declared event argument types in wire order.
func (o *WpSecurityContextManager) EventSignature(opcode uint16) (string, bool) {
	switch opcode {
	default:
		return "", false
	}
}

// Dispatch decodes one event on wp_security_context_manager_v1 and calls the registered handlers.
func (o *WpSecurityContextManager) Dispatch(event *wl.Event) {
	switch event.Opcode {
	default:
	}
}

// WpSecurityContextInterface is the protocol interface name.
const WpSecurityContextInterface = "wp_security_context_v1"

// WpSecurityContext is the generated binding for wp_security_context_v1 version 1.
type WpSecurityContext struct {
	wl.BaseProxy
}

// NewWpSecurityContext returns an unbound WpSecurityContext.
func NewWpSecurityContext(ctx *wl.Context) *WpSecurityContext {
	obj := &WpSecurityContext{}
	obj.SetContext(ctx)
	ctx.Register(obj)
	return obj
}

// Destroy the security context object.
func (o *WpSecurityContext) Destroy() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 0, Name: "wp_security_context_v1.destroy", Destructor: true}); err != nil {
		return err
	}
	return nil
}

// Attach a unique sandbox engine name to the security context. The name should follow the reverse-DNS style (e.g. "org.flatpak"). A list of well-known engines is maintained at: https://gitlab.freedesktop.org/wayland/wayland-protocols/-/blob/main/staging/security-context/engines.md It is a protocol error to call this request twice. The already_set error is sent in this case.
func (o *WpSecurityContext) SetSandboxEngine(name string) error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 1, Name: "wp_security_context_v1.set_sandbox_engine"}, wl.ArgString(name)); err != nil {
		return err
	}
	return nil
}

// Attach an application ID to the security context. The application ID is an opaque, sandbox-specific identifier for an application. See the well-known engines document for more details: https://gitlab.freedesktop.org/wayland/wayland-protocols/-/blob/main/staging/security-context/engines.md The compositor may use the application ID to group clients belonging to the same security context application. Whether this request is optional or not depends on the sandbox engine used. It is a protocol error to call this request twice. The already_set error is sent in this case.
func (o *WpSecurityContext) SetAppId(appId string) error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 2, Name: "wp_security_context_v1.set_app_id"}, wl.ArgString(appId)); err != nil {
		return err
	}
	return nil
}

// Attach an instance ID to the security context. The instance ID is an opaque, sandbox-specific identifier for a running instance of an application. See the well-known engines document for more details: https://gitlab.freedesktop.org/wayland/wayland-protocols/-/blob/main/staging/security-context/engines.md Whether this request is optional or not depends on the sandbox engine used. It is a protocol error to call this request twice. The already_set error is sent in this case.
func (o *WpSecurityContext) SetInstanceId(instanceId string) error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 3, Name: "wp_security_context_v1.set_instance_id"}, wl.ArgString(instanceId)); err != nil {
		return err
	}
	return nil
}

// Atomically register the new client and attach the security context metadata. If the provided metadata is inconsistent or does not match with out of band metadata (see https://gitlab.freedesktop.org/wayland/wayland-protocols/-/blob/main/staging/security-context/engines.md), the invalid_metadata error may be sent eventually. It's a protocol error to send any request other than "destroy" after this request. In this case, the already_used error is sent.
func (o *WpSecurityContext) Commit() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 4, Name: "wp_security_context_v1.commit"}); err != nil {
		return err
	}
	return nil
}

// EventSignature returns the declared event argument types in wire order.
func (o *WpSecurityContext) EventSignature(opcode uint16) (string, bool) {
	switch opcode {
	default:
		return "", false
	}
}

// Dispatch decodes one event on wp_security_context_v1 and calls the registered handlers.
func (o *WpSecurityContext) Dispatch(event *wl.Event) {
	switch event.Opcode {
	default:
	}
}
