// Code generated by wlbgen; DO NOT EDIT.

// Upstream protocol copyright and license:
// Copyright © 2018 Simon Ser
// Copyright © 2019 Ivan Molodetskikh
//
// Permission to use, copy, modify, distribute, and sell this
// software and its documentation for any purpose is hereby granted
// without fee, provided that the above copyright notice appear in
// all copies and that both that copyright notice and this permission
// notice appear in supporting documentation, and that the name of
// the copyright holders not be used in advertising or publicity
// pertaining to distribution of the software without specific,
// written prior permission.  The copyright holders make no
// representations about the suitability of this software for any
// purpose.  It is provided "as is" without express or implied
// warranty.
//
// THE COPYRIGHT HOLDERS DISCLAIM ALL WARRANTIES WITH REGARD TO THIS
// SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
// FITNESS, IN NO EVENT SHALL THE COPYRIGHT HOLDERS BE LIABLE FOR ANY
// SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
// AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
// ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
// THIS SOFTWARE.

package wlrdatacontrol

import (
	"fmt"
	wayland "github.com/bnema/go-wayland-bindings/server/wayland"
	"github.com/bnema/purego-libwayland/server"
	"runtime"
)

var ZwlrDataControlManagerV1Interface *server.Interface
var ZwlrDataControlDeviceV1Interface *server.Interface
var ZwlrDataControlSourceV1Interface *server.Interface
var ZwlrDataControlOfferV1Interface *server.Interface

func init() {
	ZwlrDataControlManagerV1Interface = &server.Interface{Name: "zwlr_data_control_manager_v1", Version: 2}
	ZwlrDataControlDeviceV1Interface = &server.Interface{Name: "zwlr_data_control_device_v1", Version: 2}
	ZwlrDataControlSourceV1Interface = &server.Interface{Name: "zwlr_data_control_source_v1", Version: 1}
	ZwlrDataControlOfferV1Interface = &server.Interface{Name: "zwlr_data_control_offer_v1", Version: 1}
	ZwlrDataControlManagerV1Interface.Requests = []server.Message{
		{Name: "create_data_source", Signature: "n", Types: []*server.Interface{ZwlrDataControlSourceV1Interface}},
		{Name: "get_data_device", Signature: "no", Types: []*server.Interface{ZwlrDataControlDeviceV1Interface, wayland.SeatInterface}},
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
	}
	ZwlrDataControlManagerV1Interface.Events = []server.Message{}
	ZwlrDataControlDeviceV1Interface.Requests = []server.Message{
		{Name: "set_selection", Signature: "?o", Types: []*server.Interface{ZwlrDataControlSourceV1Interface}},
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
		{Name: "set_primary_selection", Signature: "2?o", Types: []*server.Interface{ZwlrDataControlSourceV1Interface}},
	}
	ZwlrDataControlDeviceV1Interface.Events = []server.Message{
		{Name: "data_offer", Signature: "n", Types: []*server.Interface{ZwlrDataControlOfferV1Interface}},
		{Name: "selection", Signature: "?o", Types: []*server.Interface{ZwlrDataControlOfferV1Interface}},
		{Name: "finished", Signature: "", Types: []*server.Interface{}},
		{Name: "primary_selection", Signature: "2?o", Types: []*server.Interface{ZwlrDataControlOfferV1Interface}},
	}
	ZwlrDataControlSourceV1Interface.Requests = []server.Message{
		{Name: "offer", Signature: "s", Types: []*server.Interface{nil}},
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
	}
	ZwlrDataControlSourceV1Interface.Events = []server.Message{
		{Name: "send", Signature: "sh", Types: []*server.Interface{nil, nil}},
		{Name: "cancelled", Signature: "", Types: []*server.Interface{}},
	}
	ZwlrDataControlOfferV1Interface.Requests = []server.Message{
		{Name: "receive", Signature: "sh", Types: []*server.Interface{nil, nil}},
		{Name: "destroy", Signature: "", Types: []*server.Interface{}},
	}
	ZwlrDataControlOfferV1Interface.Events = []server.Message{
		{Name: "offer", Signature: "s", Types: []*server.Interface{nil}},
	}
	if err := server.NewInterfaces(ZwlrDataControlManagerV1Interface, ZwlrDataControlDeviceV1Interface, ZwlrDataControlSourceV1Interface, ZwlrDataControlOfferV1Interface); err != nil {
		panic(err)
	}
}

// ZwlrDataControlManagerV1 manager to control data devices.
type ZwlrDataControlManagerV1 struct{ *server.Resource }

func WrapZwlrDataControlManagerV1(r *server.Resource) *ZwlrDataControlManagerV1 {
	if r == nil {
		return nil
	}
	return &ZwlrDataControlManagerV1{r}
}

const ZwlrDataControlManagerV1RequestCreateDataSource uint32 = 0
const ZwlrDataControlManagerV1RequestGetDataDevice uint32 = 1
const ZwlrDataControlManagerV1RequestDestroy uint32 = 2

// ZwlrDataControlManagerV1Handler handles zwlr_data_control_manager_v1 requests.
type ZwlrDataControlManagerV1Handler interface {
	CreateDataSource(self *ZwlrDataControlManagerV1, id uint32)
	GetDataDevice(self *ZwlrDataControlManagerV1, id uint32, seat *wayland.Seat)
	Destroy(self *ZwlrDataControlManagerV1)
}

func NewZwlrDataControlManagerV1(c server.Client, version int32, id uint32, h ZwlrDataControlManagerV1Handler) (*ZwlrDataControlManagerV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for zwlr_data_control_manager_v1")
	}
	var self *ZwlrDataControlManagerV1
	r, err := c.CreateResource(ZwlrDataControlManagerV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.CreateDataSource(self, args[0].NewID())
		case 1:
			h.GetDataDevice(self, args[0].NewID(), wayland.WrapSeat(args[1].Resource()))
		case 2:
			h.Destroy(self)
			self.Destroy()
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapZwlrDataControlManagerV1(r)
	r.Data = self
	return self, nil
}
func NewZwlrDataControlManagerV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(ZwlrDataControlManagerV1Interface, version, bind)
}

// ZwlrDataControlDeviceV1 manage a data device for a seat.
type ZwlrDataControlDeviceV1 struct{ *server.Resource }

func WrapZwlrDataControlDeviceV1(r *server.Resource) *ZwlrDataControlDeviceV1 {
	if r == nil {
		return nil
	}
	return &ZwlrDataControlDeviceV1{r}
}

const ZwlrDataControlDeviceV1RequestSetSelection uint32 = 0
const ZwlrDataControlDeviceV1RequestDestroy uint32 = 1
const ZwlrDataControlDeviceV1RequestSetPrimarySelection uint32 = 2
const ZwlrDataControlDeviceV1EventDataOffer uint32 = 0
const ZwlrDataControlDeviceV1EventSelection uint32 = 1
const ZwlrDataControlDeviceV1EventFinished uint32 = 2
const ZwlrDataControlDeviceV1EventPrimarySelection uint32 = 3

// ZwlrDataControlDeviceV1Error .
type ZwlrDataControlDeviceV1Error uint32

const (
	ZwlrDataControlDeviceV1ErrorUsedSource ZwlrDataControlDeviceV1Error = 1
)

// ZwlrDataControlDeviceV1Handler handles zwlr_data_control_device_v1 requests.
type ZwlrDataControlDeviceV1Handler interface {
	SetSelection(self *ZwlrDataControlDeviceV1, source *ZwlrDataControlSourceV1)
	Destroy(self *ZwlrDataControlDeviceV1)
	SetPrimarySelection(self *ZwlrDataControlDeviceV1, source *ZwlrDataControlSourceV1)
}

func NewZwlrDataControlDeviceV1(c server.Client, version int32, id uint32, h ZwlrDataControlDeviceV1Handler) (*ZwlrDataControlDeviceV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for zwlr_data_control_device_v1")
	}
	var self *ZwlrDataControlDeviceV1
	r, err := c.CreateResource(ZwlrDataControlDeviceV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.SetSelection(self, WrapZwlrDataControlSourceV1(args[0].Resource()))
		case 1:
			h.Destroy(self)
			self.Destroy()
		case 2:
			h.SetPrimarySelection(self, WrapZwlrDataControlSourceV1(args[0].Resource()))
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapZwlrDataControlDeviceV1(r)
	r.Data = self
	return self, nil
}

// SendDataOffer introduce a new wlr_data_control_offer.
func (self *ZwlrDataControlDeviceV1) SendDataOffer(id *ZwlrDataControlOfferV1) {
	self.PostEvent(ZwlrDataControlDeviceV1EventDataOffer, server.NewID(resourceOf(id)))
}

// SendSelection advertise new selection.
func (self *ZwlrDataControlDeviceV1) SendSelection(id *ZwlrDataControlOfferV1) {
	self.PostEvent(ZwlrDataControlDeviceV1EventSelection, server.Object(resourceOf(id)))
}

// SendFinished this data control is no longer valid.
func (self *ZwlrDataControlDeviceV1) SendFinished() {
	self.PostEvent(ZwlrDataControlDeviceV1EventFinished)
}

// SendPrimarySelection advertise new primary selection (since version 2).
func (self *ZwlrDataControlDeviceV1) SendPrimarySelection(id *ZwlrDataControlOfferV1) {
	self.PostEvent(ZwlrDataControlDeviceV1EventPrimarySelection, server.Object(resourceOf(id)))
}
func NewZwlrDataControlDeviceV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(ZwlrDataControlDeviceV1Interface, version, bind)
}

// ZwlrDataControlSourceV1 offer to transfer data.
type ZwlrDataControlSourceV1 struct{ *server.Resource }

func WrapZwlrDataControlSourceV1(r *server.Resource) *ZwlrDataControlSourceV1 {
	if r == nil {
		return nil
	}
	return &ZwlrDataControlSourceV1{r}
}

const ZwlrDataControlSourceV1RequestOffer uint32 = 0
const ZwlrDataControlSourceV1RequestDestroy uint32 = 1
const ZwlrDataControlSourceV1EventSend uint32 = 0
const ZwlrDataControlSourceV1EventCancelled uint32 = 1

// ZwlrDataControlSourceV1Error .
type ZwlrDataControlSourceV1Error uint32

const (
	ZwlrDataControlSourceV1ErrorInvalidOffer ZwlrDataControlSourceV1Error = 1
)

// ZwlrDataControlSourceV1Handler handles zwlr_data_control_source_v1 requests.
type ZwlrDataControlSourceV1Handler interface {
	Offer(self *ZwlrDataControlSourceV1, mimeType string)
	Destroy(self *ZwlrDataControlSourceV1)
}

func NewZwlrDataControlSourceV1(c server.Client, version int32, id uint32, h ZwlrDataControlSourceV1Handler) (*ZwlrDataControlSourceV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for zwlr_data_control_source_v1")
	}
	var self *ZwlrDataControlSourceV1
	r, err := c.CreateResource(ZwlrDataControlSourceV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Offer(self, args[0].String())
		case 1:
			h.Destroy(self)
			self.Destroy()
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapZwlrDataControlSourceV1(r)
	r.Data = self
	return self, nil
}

// SendSend send the data.
func (self *ZwlrDataControlSourceV1) SendSend(mimeType string, fd int) {
	var p runtime.Pinner
	defer p.Unpin()
	self.PostEvent(ZwlrDataControlSourceV1EventSend, server.String(&p, mimeType, false), server.Fd(fd))
}

// SendCancelled selection was cancelled.
func (self *ZwlrDataControlSourceV1) SendCancelled() {
	self.PostEvent(ZwlrDataControlSourceV1EventCancelled)
}
func NewZwlrDataControlSourceV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(ZwlrDataControlSourceV1Interface, version, bind)
}

// ZwlrDataControlOfferV1 offer to transfer data.
type ZwlrDataControlOfferV1 struct{ *server.Resource }

func WrapZwlrDataControlOfferV1(r *server.Resource) *ZwlrDataControlOfferV1 {
	if r == nil {
		return nil
	}
	return &ZwlrDataControlOfferV1{r}
}

const ZwlrDataControlOfferV1RequestReceive uint32 = 0
const ZwlrDataControlOfferV1RequestDestroy uint32 = 1
const ZwlrDataControlOfferV1EventOffer uint32 = 0

// ZwlrDataControlOfferV1Handler handles zwlr_data_control_offer_v1 requests.
type ZwlrDataControlOfferV1Handler interface {
	Receive(self *ZwlrDataControlOfferV1, mimeType string, fd int)
	Destroy(self *ZwlrDataControlOfferV1)
}

func NewZwlrDataControlOfferV1(c server.Client, version int32, id uint32, h ZwlrDataControlOfferV1Handler) (*ZwlrDataControlOfferV1, error) {
	if h == nil {
		return nil, fmt.Errorf("purego-libwayland: nil handler for zwlr_data_control_offer_v1")
	}
	var self *ZwlrDataControlOfferV1
	r, err := c.CreateResource(ZwlrDataControlOfferV1Interface, version, id, func(_ *server.Resource, opcode uint32, args []server.Arg) {
		switch opcode {
		case 0:
			h.Receive(self, args[0].String(), args[1].Fd())
		case 1:
			h.Destroy(self)
			self.Destroy()
		}
	})
	if err != nil {
		return nil, err
	}
	self = WrapZwlrDataControlOfferV1(r)
	r.Data = self
	return self, nil
}

// SendOffer advertise offered MIME type.
func (self *ZwlrDataControlOfferV1) SendOffer(mimeType string) {
	var p runtime.Pinner
	defer p.Unpin()
	self.PostEvent(ZwlrDataControlOfferV1EventOffer, server.String(&p, mimeType, false))
}
func NewZwlrDataControlOfferV1Global(d *server.Display, version int32, bind server.BindFunc) error {
	return d.CreateGlobal(ZwlrDataControlOfferV1Interface, version, bind)
}
func resourceOf(v interface{ GetResource() *server.Resource }) *server.Resource {
	if v == nil {
		return nil
	}
	return v.GetResource()
}
func (self *ZwlrDataControlManagerV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *ZwlrDataControlDeviceV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *ZwlrDataControlSourceV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
func (self *ZwlrDataControlOfferV1) GetResource() *server.Resource {
	if self == nil {
		return nil
	}
	return self.Resource
}
