// Code generated by wlbgen. DO NOT EDIT.
// Protocol: xdg_session_management_v1
// Source: xdg-session-management-v1.xml

// Upstream protocol copyright and license:
// Copyright 2018 Mike Blumenkrantz
// Copyright 2018 Samsung Electronics Co., Ltd
// Copyright 2018 Red Hat Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package xdgsessionmanagement

import (
	"sync"

	cross_xdg_toplevel "github.com/bnema/go-wayland-bindings/client/xdgshell"
	"github.com/bnema/wlturbo/wl"
)

// ERROR_IN_USE is the error in_use value.
const ERROR_IN_USE = 1

// ERROR_INVALID_SESSION_ID is the error invalid_session_id value.
const ERROR_INVALID_SESSION_ID = 2

// ERROR_INVALID_REASON is the error invalid_reason value.
const ERROR_INVALID_REASON = 3

// REASON_LAUNCH is the reason launch value.
const REASON_LAUNCH = 1

// REASON_RECOVER is the reason recover value.
const REASON_RECOVER = 2

// REASON_SESSION_RESTORE is the reason session_restore value.
const REASON_SESSION_RESTORE = 3

// ERROR_NAME_IN_USE is the error name_in_use value.
const ERROR_NAME_IN_USE = 1

// ERROR_ALREADY_MAPPED is the error already_mapped value.
const ERROR_ALREADY_MAPPED = 2

// ERROR_INVALID_NAME is the error invalid_name value.
const ERROR_INVALID_NAME = 3

// ERROR_ALREADY_ADDED is the error already_added value.
const ERROR_ALREADY_ADDED = 4

// XdgSessionManagerInterface is the protocol interface name.
const XdgSessionManagerInterface = "xdg_session_manager_v1"

// XdgSessionManager is the generated binding for xdg_session_manager_v1 version 1.
type XdgSessionManager struct {
	wl.BaseProxy
}

// NewXdgSessionManager returns an unbound XdgSessionManager.
func NewXdgSessionManager(ctx *wl.Context) *XdgSessionManager {
	obj := &XdgSessionManager{}
	obj.SetContext(ctx)
	ctx.Register(obj)
	return obj
}

// Destroy the manager object. The existing session objects will be unaffected.
func (o *XdgSessionManager) Destroy() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 0, Name: "xdg_session_manager_v1.destroy", Destructor: true}); err != nil {
		return err
	}
	return nil
}

// Create a session object corresponding to either an existing session identified by the given session identifier string or a new session. While the session object exists, the session is considered to be "in use". If an identifier string represents a session that is currently actively in use by the the same client, an 'in_use' error is raised. If some other client is currently using the same session, the new session will replace managing the associated state. If the reason is not a valid enum entry, the 'invalid_reason' protocol error is raised. NULL is passed to initiate a new session. If a session_id is passed which does not represent a valid session, the compositor treats it as if NULL had been passed. The session id string must be UTF-8 encoded. It is also limited by the maximum length of wayland messages (around 4KB). The 'invalid_session_id' protocol error will be raised if an invalid string is provided. A client is allowed to have any number of in use sessions at the same time.
func (o *XdgSessionManager) GetSession(reason uint32, sessionId string) (*XdgSession, error) {
	child := &XdgSession{}
	child.SetContext(o.Context())
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 1, Name: "xdg_session_manager_v1.get_session", Child: child}, wl.ArgObject(child), wl.ArgUint(reason), wl.ArgString(sessionId)); err != nil {
		return nil, err
	}
	return child, nil
}

// EventSignature returns the declared event argument types in wire order.
func (o *XdgSessionManager) EventSignature(opcode uint16) (string, bool) {
	switch opcode {
	default:
		return "", false
	}
}

// Dispatch decodes one event on xdg_session_manager_v1 and calls the registered handlers.
func (o *XdgSessionManager) Dispatch(event *wl.Event) {
	switch event.Opcode {
	default:
	}
}

// XdgSessionInterface is the protocol interface name.
const XdgSessionInterface = "xdg_session_v1"

// XdgSession is the generated binding for xdg_session_v1 version 1.
type XdgSession struct {
	wl.BaseProxy
	// handlersMu guards the handler slices: a client may register or replace
	// handlers while another goroutine dispatches events.
	handlersMu sync.Mutex
	onCreated  []func(sessionId string)
	onRestored []func()
	onReplaced []func()
}

// NewXdgSession returns an unbound XdgSession.
func NewXdgSession(ctx *wl.Context) *XdgSession {
	obj := &XdgSession{}
	obj.SetContext(ctx)
	ctx.Register(obj)
	return obj
}

// Destroy a session object, preserving the current state but not continuing to make further updates if state changes occur. This makes the associated xdg_toplevel_session_v1 objects inert.
func (o *XdgSession) Destroy() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 0, Name: "xdg_session_v1.destroy", Destructor: true}); err != nil {
		return err
	}
	return nil
}

// Remove the session, making it no longer available for restoration. A compositor should in response to this request remove the data related to this session from its storage.
func (o *XdgSession) Remove() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 1, Name: "xdg_session_v1.remove", Destructor: true}); err != nil {
		return err
	}
	return nil
}

// Attempt to add a given surface to the session. The passed name is used to identify what window is being restored, and may be used to store window specific state within the session. The name given to the toplevel must not correspond to any previously existing toplevel names in the session. If the name matches an already known toplevel name in the session, a 'name_in_use' protocol error will be raised. The toplevel object must not be added more than once to any session created by the client, otherwise the 'already_added' protocol error will be raised. This request will return a xdg_toplevel_session_v1 for later manipulation. As this resource is created from an empty initial state, compositors must not emit a xdg_toplevel_session_v1.restored event for resources created through this request. The name string must be UTF-8 encoded. It is also limited by the maximum length of wayland messages (around 4KB). The 'invalid_name' protocol error will be raised if an invalid string is provided.
func (o *XdgSession) AddToplevel(toplevel *cross_xdg_toplevel.XdgToplevel, name string) (*XdgToplevelSession, error) {
	var arg1 wl.Object
	if toplevel != nil {
		arg1 = toplevel
	}
	child := &XdgToplevelSession{}
	child.SetContext(o.Context())
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 2, Name: "xdg_session_v1.add_toplevel", Child: child}, wl.ArgObject(child), wl.ArgObject(arg1), wl.ArgString(name)); err != nil {
		return nil, err
	}
	return child, nil
}

// Inform the compositor that the toplevel associated with the passed name should have its window management state restored. If the toplevel name was previously granted to another xdg_toplevel, the 'name_in_use' protocol error will be raised. The toplevel object must not be added more than once to any session created by the client, otherwise the 'already_added' protocol error will be raised. This request must be called prior to the first commit on the associated wl_surface after creating the toplevel, otherwise an 'already_mapped' error is raised. As part of the initial configure sequence, if the toplevel was successfully restored, a xdg_toplevel_session_v1.restored event is emitted. If the toplevel name was not known in the session, this request will be equivalent to the xdg_toplevel_session_v1.add_toplevel request, and no such event will be emitted. See the xdg_toplevel_session_v1.restored event for further details. The name string must be UTF-8 encoded. It is also limited by the maximum length of wayland messages (around 4KB). The 'invalid_name' protocol error will be raised if an invalid string is provided.
func (o *XdgSession) RestoreToplevel(toplevel *cross_xdg_toplevel.XdgToplevel, name string) (*XdgToplevelSession, error) {
	var arg1 wl.Object
	if toplevel != nil {
		arg1 = toplevel
	}
	child := &XdgToplevelSession{}
	child.SetContext(o.Context())
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 3, Name: "xdg_session_v1.restore_toplevel", Child: child}, wl.ArgObject(child), wl.ArgObject(arg1), wl.ArgString(name)); err != nil {
		return nil, err
	}
	return child, nil
}

// Remove a specified surface from the session and render any related xdg_toplevel_session_v1 object inert. The compositor should remove any data related to the toplevel in the corresponding session from its internal storage. The window is specified by its name in the session. The name string must be encoded in UTF-8, and it is limited in size by the maximum length of wayland messages (around 4KB).
func (o *XdgSession) RemoveToplevel(name string) error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 4, Name: "xdg_session_v1.remove_toplevel"}, wl.ArgString(name)); err != nil {
		return err
	}
	return nil
}

// OnCreated registers a handler for the created event.
//
// Handlers are appended, so a second call adds another handler rather than
// replacing the first. Registration is safe while another goroutine dispatches.
func (o *XdgSession) OnCreated(handler func(sessionId string)) {
	if handler == nil {
		return
	}
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	o.onCreated = append(o.onCreated, handler)
}

// handlersForCreated returns the handlers registered for created, taken
// under the lock so a handler may register another handler while events are
// being dispatched.
func (o *XdgSession) handlersForCreated() []func(sessionId string) {
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	return o.onCreated
}

// OnRestored registers a handler for the restored event.
//
// Handlers are appended, so a second call adds another handler rather than
// replacing the first. Registration is safe while another goroutine dispatches.
func (o *XdgSession) OnRestored(handler func()) {
	if handler == nil {
		return
	}
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	o.onRestored = append(o.onRestored, handler)
}

// handlersForRestored returns the handlers registered for restored, taken
// under the lock so a handler may register another handler while events are
// being dispatched.
func (o *XdgSession) handlersForRestored() []func() {
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	return o.onRestored
}

// OnReplaced registers a handler for the replaced event.
//
// Handlers are appended, so a second call adds another handler rather than
// replacing the first. Registration is safe while another goroutine dispatches.
func (o *XdgSession) OnReplaced(handler func()) {
	if handler == nil {
		return
	}
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	o.onReplaced = append(o.onReplaced, handler)
}

// handlersForReplaced returns the handlers registered for replaced, taken
// under the lock so a handler may register another handler while events are
// being dispatched.
func (o *XdgSession) handlersForReplaced() []func() {
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	return o.onReplaced
}

// EventSignature returns the declared event argument types in wire order.
func (o *XdgSession) EventSignature(opcode uint16) (string, bool) {
	switch opcode {
	case 0:
		return "string,", true
	case 1:
		return "", true
	case 2:
		return "", true
	default:
		return "", false
	}
}

// Dispatch decodes one event on xdg_session_v1 and calls the registered handlers.
func (o *XdgSession) Dispatch(event *wl.Event) {
	switch event.Opcode {
	case 0: // created
		sessionId := event.String()

		for i, handler := range o.handlersForCreated() {
			_ = i
			handler(sessionId)
		}
	case 1: // restored

		for i, handler := range o.handlersForRestored() {
			_ = i
			handler()
		}
	case 2: // replaced

		for i, handler := range o.handlersForReplaced() {
			_ = i
			handler()
		}
	default:
	}
}

// XdgToplevelSessionInterface is the protocol interface name.
const XdgToplevelSessionInterface = "xdg_toplevel_session_v1"

// XdgToplevelSession is the generated binding for xdg_toplevel_session_v1 version 1.
type XdgToplevelSession struct {
	wl.BaseProxy
	// handlersMu guards the handler slices: a client may register or replace
	// handlers while another goroutine dispatches events.
	handlersMu sync.Mutex
	onRestored []func()
}

// NewXdgToplevelSession returns an unbound XdgToplevelSession.
func NewXdgToplevelSession(ctx *wl.Context) *XdgToplevelSession {
	obj := &XdgToplevelSession{}
	obj.SetContext(ctx)
	ctx.Register(obj)
	return obj
}

// Destroy the object. This has no effect over window management of the associated toplevel.
func (o *XdgToplevelSession) Destroy() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 0, Name: "xdg_toplevel_session_v1.destroy", Destructor: true}); err != nil {
		return err
	}
	return nil
}

// Renames the toplevel session. The new name can be used in subsequent requests to identify this session object. The state associated with this toplevel session will be preserved. If the xdg_session_v1 already contains a toplevel with the specified name, the 'name_in_use' protocol error will be raised.
func (o *XdgToplevelSession) Rename(name string) error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 1, Name: "xdg_toplevel_session_v1.rename"}, wl.ArgString(name)); err != nil {
		return err
	}
	return nil
}

// OnRestored registers a handler for the restored event.
//
// Handlers are appended, so a second call adds another handler rather than
// replacing the first. Registration is safe while another goroutine dispatches.
func (o *XdgToplevelSession) OnRestored(handler func()) {
	if handler == nil {
		return
	}
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	o.onRestored = append(o.onRestored, handler)
}

// handlersForRestored returns the handlers registered for restored, taken
// under the lock so a handler may register another handler while events are
// being dispatched.
func (o *XdgToplevelSession) handlersForRestored() []func() {
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	return o.onRestored
}

// EventSignature returns the declared event argument types in wire order.
func (o *XdgToplevelSession) EventSignature(opcode uint16) (string, bool) {
	switch opcode {
	case 0:
		return "", true
	default:
		return "", false
	}
}

// Dispatch decodes one event on xdg_toplevel_session_v1 and calls the registered handlers.
func (o *XdgToplevelSession) Dispatch(event *wl.Event) {
	switch event.Opcode {
	case 0: // restored

		for i, handler := range o.handlersForRestored() {
			_ = i
			handler()
		}
	default:
	}
}
